"use client";
import {useId,useRef,useState,type PointerEvent} from 'react';
import {Button} from '@/components/ui/button';
import {C,num} from './lab-common';
import {AngleControl} from './circuit-controls';
import {blochCoordinates,dragBlochPoint,fromBlochAngles,toView,rotateView,qubitName} from '@/lib/bloch-interaction';
import {initialStates,probabilityH} from '@/lib/quantum-experiments';
import {type Vector} from '@/lib/physics';

export function BlochPoint({v,onChange,axis,path,compact=false,showAxes=false,angleTo,label='Stato sulla sfera di Bloch'}:{v:Vector;onChange?:(v:Vector)=>void;axis?:Vector;path?:Vector[];compact?:boolean;showAxes?:boolean;angleTo?:Vector;label?:string}){
 const [viewAngle,setViewAngle]=useState(0);const id=useId(),drag=useRef<{v:Vector;pointer:Vector;id:number}|null>(null),cx=160,cy=139,r=99;
 const project=(p:Vector)=>{const u=toView(rotateView(p,viewAngle));return [cx+r*u[0],cy-r*u[1]];},[x,y]=project(v),back=toView(rotateView(v,viewAngle))[2]<0,coordinates=blochCoordinates(v);

 const arc=angleTo?(()=>{const dot=Math.max(-1,Math.min(1,v.reduce((sum,x,i)=>sum+x*angleTo[i],0))),beta=Math.acos(dot);let tangent=v.map((x,i)=>x-dot*angleTo[i]) as Vector;let length=Math.hypot(...tangent);if(length<1e-8){const ref:Vector=Math.abs(angleTo[2])<.9?[0,0,1]:[1,0,0];tangent=[angleTo[1]*ref[2]-angleTo[2]*ref[1],angleTo[2]*ref[0]-angleTo[0]*ref[2],angleTo[0]*ref[1]-angleTo[1]*ref[0]];length=Math.hypot(...tangent);}tangent=tangent.map(x=>x/length) as Vector;return{beta,points:Array.from({length:49},(_,j)=>angleTo.map((x,i)=>.58*(x*Math.cos(beta*j/48)+tangent[i]*Math.sin(beta*j/48))) as Vector)};})():null;
 const pointer=(e:PointerEvent<SVGSVGElement>):Vector|null=>{const matrix=e.currentTarget.getScreenCTM();if(!matrix)return null;const p=e.currentTarget.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(matrix.inverse());return [(q.x-cx)/r,(cy-q.y)/r,0];};
 const move=(e:PointerEvent<SVGSVGElement>)=>{const start=drag.current,p=pointer(e);if(start&&p&&start.id===e.pointerId)onChange?.(dragBlochPoint(start.v,p[0]-start.pointer[0],p[1]-start.pointer[1],viewAngle));};
 return <div className={'bloch-point'+(compact?' compact':'')+(onChange?' editable':'')}>
 <svg viewBox="0 0 320 275" role={onChange?'group':'img'} tabIndex={onChange?0:undefined} aria-label={label} aria-describedby={onChange?id:undefined}
 onPointerDown={onChange?e=>{if(e.button!==0)return;const p=pointer(e);if(!p)return;const u=toView(rotateView(v,viewAngle));if(Math.hypot(p[0]-u[0],p[1]-u[1])>.22)return;e.preventDefault();e.currentTarget.focus({preventScroll:true});e.currentTarget.setPointerCapture(e.pointerId);drag.current={v:[...v],pointer:p,id:e.pointerId};}:undefined}
 onPointerMove={onChange?move:undefined} onPointerUp={onChange?e=>{move(e);drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}:undefined}
 onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}
 onKeyDown={onChange?e=>{const step=e.shiftKey?1:5;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();if(e.key==='Home')onChange(initialStates.H);else if(e.key==='End')onChange(initialStates.V);else onChange(fromBlochAngles(Math.max(0,Math.min(180,coordinates.inclination+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0))),(coordinates.phase+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)+360)%360));}}:undefined}>
 <title>{label+' · '+qubitName(v)}</title><circle cx={cx} cy={cy} r={r} fill="var(--mq-surface)" stroke="var(--mq-wire)" strokeWidth="1.5"/>
 <ellipse cx={cx} cy={cy} rx={r} ry={r*.28} fill="none" stroke="var(--mq-wire)" strokeDasharray="4 5"/><path d={'M'+(cx-r)+' '+cy+'A'+r+' '+r*.28+' 0 0 0 '+(cx+r)+' '+cy} fill="none" stroke="var(--mq-wire)"/>
 {[0,1].map(plane=><path key={plane} d={Array.from({length:97},(_,i)=>{const t=i*Math.PI/48;return (i?'L':'M')+project(plane?[Math.cos(t),0,Math.sin(t)]:[0,Math.cos(t),Math.sin(t)]).join(' ');}).join(' ')} fill="none" stroke="var(--mq-wire)" strokeDasharray="4 5"/>)}<path d={'M'+cx+' '+(cy-r*.96)+'V'+(cy+r*.96)+'M'+(cx-r)+' '+cy+'H'+(cx+r)} stroke="var(--mq-wire)"/>
 {showAxes&&([['X',[1,0,0]],['Y',[0,1,0]],['Z',[0,0,1]]] as [string,Vector][]).map(([name,direction])=><g key={name}><line x1={cx} y1={cy} x2={project(direction)[0]} y2={project(direction)[1]} stroke="var(--mq-wire)" strokeDasharray="3 4"/><text x={project(direction)[0]-16} y={project(direction)[1]-12} fontSize="15" fill={C.ink}>{name}</text></g>)}
 {arc&&<><path d={arc.points.map((p,i)=>(i?'L':'M')+project(p).join(' ')).join(' ')} fill="none" stroke="var(--mq-violet)" strokeWidth="3"/><text x={project(arc.points[24])[0]+7} y={project(arc.points[24])[1]-8} fill="var(--mq-violet)" fontSize="15">β={num(arc.beta*180/Math.PI,1)}°</text></>}
 {axis&&<line x1={project(axis.map(x=>-x) as Vector)[0]} y1={project(axis.map(x=>-x) as Vector)[1]} x2={project(axis)[0]} y2={project(axis)[1]} stroke={C.green} strokeWidth="2" strokeDasharray="5 4"/>}
 {path&&path.length>1&&<><defs><marker id={id+'path'} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10Z" fill={C.green}/></marker></defs><path d={path.map((p,i)=>(i?'L':'M')+project(p).join(' ')).join(' ')} fill="none" stroke={C.green} strokeWidth="2.5" opacity=".85" markerEnd={'url(#'+id+'path)'}/><circle cx={project(path[0])[0]} cy={project(path[0])[1]} r="4" fill="var(--mq-panel)" stroke={C.green} strokeWidth="2"/></>}
 <line x1={cx} y1={cy} x2={x} y2={y} stroke={C.red} strokeWidth="3.2" strokeDasharray={back?'5 3':undefined}/><circle cx={x} cy={y} r={onChange?8:5} fill={C.red} stroke="var(--mq-on-accent)" strokeWidth="2"/>{onChange&&<circle cx={x} cy={y} r="14" fill="none" stroke={C.red} opacity=".25"/>}<circle cx={cx} cy={cy} r="2.5" fill={C.ink}/>
 <text x={cx+13} y={cy-r*.96-8} fontSize="16" fill={C.blue}>0</text><text x={cx+13} y={cy+r*.96+17} fontSize="16" fill={C.blue}>1</text><text x={project([1,0,0])[0]+13} y={project([1,0,0])[1]+5} fontSize="14" fill={C.gray}>+</text><text x={project([-1,0,0])[0]-13} y={project([-1,0,0])[1]+5} textAnchor="end" fontSize="14" fill={C.gray}>−</text>
 </svg>
 {onChange&&<p className="bloch-drag-hint" id={id}>{compact?'Trascina il punto blu.':'Trascina il punto blu per cambiare la preparazione. Le frecce della tastiera regolano inclinazione e fase; Maiusc riduce il passo, Inizio e Fine selezionano i poli. Al bordo della sfera, ruota la vista per proseguire sull’altro emisfero.'}</p>}
 {onChange&&<div className="view-controls" aria-label="Punto di osservazione della sfera"><Button variant="outline" aria-label="Ruota la vista di trenta gradi a sinistra" onClick={()=>setViewAngle(a=>a-30)}>↶ Vista</Button><Button variant="outline" aria-label="Ruota la vista di trenta gradi a destra" onClick={()=>setViewAngle(a=>a+30)}>Vista ↷</Button>{viewAngle!==0&&<Button variant="ghost" onClick={()=>setViewAngle(0)}>Vista iniziale</Button>}<small>Ruotare la vista conserva lo stato.</small></div>}
 </div>;
}
export function SourcePreparation({v,onChange}:{v:Vector;onChange:(v:Vector)=>void}){
 const a=blochCoordinates(v),p=probabilityH(v);
 return <section className="source-preparation"><div className="source-geometry"><span className="circuit-eyebrow">IL QUBIT ALL’INGRESSO</span><h3>Prepara il punto sulla sfera</h3><BlochPoint v={v} onChange={onChange}/><strong>{qubitName(v)}</strong><p>0: {num(p*100,1)}% · 1: {num((1-p)*100,1)}%<br/>{a.hasPhase?'Fase relativa '+num(a.phase,1)+'°':'Ai poli è presente una sola componente: la fase relativa non è definita.'}</p></div><div className="source-settings"><p>Muovere il punto cambia lo stato iniziale del qubit. Tutti i blocchi vengono applicati di nuovo a questo stato e la previsione finale si aggiorna insieme alle sfere intermedie. Il tratteggio della freccia indica che il punto si trova sulla metà posteriore della sfera.</p><div className="source-presets">{Object.entries({...initialStates,Cm:[0,-1,0] as Vector}).map(([key,state])=><Button key={key} variant={v.every((x,i)=>Math.abs(x-state[i])<1e-7)?'default':'outline'} onClick={()=>onChange([...state])}>{key==='H'?'0':key==='V'?'1':key==='D'?'+':key==='A'?'−':key==='C'?'Fase +90°':'Fase −90°'}</Button>)}</div><AngleControl label="Distanza angolare dal polo 0" value={a.inclination} max={180} onChange={t=>onChange(fromBlochAngles(t,a.phase))}/><AngleControl label="Fase relativa dello stato" min={-360} value={a.hasPhase?a.phase:0} onChange={phase=>onChange(fromBlochAngles(a.inclination,phase))} disabled={!a.hasPhase}/><p>Il polo superiore dà 0 con certezza; quello inferiore dà 1 con certezza. Sull’equatore i due esiti hanno la stessa probabilità. Muoversi lungo un parallelo conserva queste probabilità e cambia la fase relativa. Puoi inserire anche una fase negativa: −90° e +270° individuano lo stesso punto. Le fasi dello stato sono riportate fra −180° e +180°; la distanza dal polo 0 varia fra 0° e 180°.</p></div></section>;
}
