"use client";
import {type ReactNode,useId,useContext} from 'react';
import {LabReadingContext} from './lab-reading';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Bloch,C,num,Stage} from './lab-common';
import {amplitudes,probabilityH,stateName} from '@/lib/quantum-experiments';
import {type Vector} from '@/lib/physics';

export function Notebook({intro,experiments,controls,children,result,model,overview}:{intro:ReactNode;experiments:ReactNode;controls:ReactNode;children:ReactNode;result:ReactNode;model:ReactNode;overview?:ReactNode}){
 const id=useId(),lab=useContext(LabReadingContext);
 const jump=(suffix:string)=>{const el=document.getElementById(id+suffix);el?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});el?.focus({preventScroll:true});};
 return <div className="quantum-notebook"><p className="notebook-intro">{intro}</p><div className="experiment-presets">{experiments}</div>{lab!=='sintesi'&&<p className="notation-key"><strong>Le stesse preparazioni:</strong> 0 = H · 1 = V · + = diagonale +45° · − = diagonale −45°. Le lettere A e B, quando compaiono, indicano le uscite della misura scelta.</p>}<nav className="notebook-navigation" aria-label="Muoversi nell’esperimento">{overview&&<Button variant="outline" onClick={()=>jump("overview")}>Circuito completo</Button>}<Button variant="outline" onClick={()=>jump("controls")}>Regolazioni</Button><Button variant="outline" onClick={()=>jump("apparatus")}>{overview?'Operazioni e risultati':'Apparato e risultati'}</Button><Button variant="outline" onClick={()=>jump("conclusion")}>Interpretazione</Button></nav>{overview&&<section className="notebook-overview" id={id+"overview"} tabIndex={-1}>{overview}</section>}<div className="notebook-bench"><aside className="notebook-controls" id={id+"controls"} tabIndex={-1}><h2>Preparare e intervenire</h2>{controls}</aside><div className="notebook-apparatus" id={id+"apparatus"} tabIndex={-1}>{children}</div></div><section className="notebook-conclusion" id={id+"conclusion"} tabIndex={-1} aria-live="polite"><h2>Che cosa mostra questa configurazione</h2>{result}</section><details className="model-details"><summary>Il modello e le sue condizioni</summary><div>{model}</div></details></div>;
}
export function Preset({children,onClick,active=false}:{children:ReactNode;onClick:()=>void;active?:boolean}){return <Button className="experiment-preset" variant={active?'default':'outline'} onClick={onClick} aria-pressed={active}>{children}</Button>;}
export function Explain({children}:{children:ReactNode}){return <div className="instrument-explanation">{children}</div>;}
export function Toggle({label,checked,onChange,children,disabled=false}:{label:string;checked:boolean;onChange:(b:boolean)=>void;children?:ReactNode;disabled?:boolean}){const id=useId();return <div className="instrument-toggle"><div><label htmlFor={id}>{label}</label><Switch id={id} checked={checked} onCheckedChange={onChange} disabled={disabled}/></div>{children&&<Explain>{children}</Explain>}</div>;}
export function Reading({title,children}:{title:string;children:ReactNode}){return <section className="notebook-reading"><h3>{title}</h3>{children}</section>;}
export function SlideLink({page,children}:{page:number;children:ReactNode}){return <a className="slide-experiment-link" href={'./presentazione.pdf#page='+page} target="_blank" rel="noreferrer">{children} ↗</a>;}
export function ProbabilityMeter({p,label}:{p:number;label:string}){return <div className="prediction-meter"><div><span>{label}</span><strong>{num(p*100,1)}%</strong></div><div className="prediction-track"><span style={{width:p*100+'%'}}/></div></div>;}
export function Polarization({v,cx,cy,r=50}:{v:Vector;cx:number;cy:number;r?:number}){const [a,b]=amplitudes(v),points=Array.from({length:101},(_,i)=>{const t=i/100*2*Math.PI;return [cx+r*a[0]*Math.cos(t),cy-r*(b[0]*Math.cos(t)+b[1]*Math.sin(t))];});return <g><circle cx={cx} cy={cy} r={r+5} fill="var(--mq-panel)" stroke={C.line}/><line x1={cx-r-9} x2={cx+r+9} y1={cy} y2={cy} stroke={C.line}/><line x1={cx} x2={cx} y1={cy-r-9} y2={cy+r+9} stroke={C.line}/><path d={points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ')} fill="none" stroke={C.blue} strokeWidth="3"/><text x={cx+r+12} y={cy+5} fill={C.gray} fontSize="17">H</text><text x={cx} y={cy-r-15} textAnchor="middle" fill={C.gray} fontSize="17">V</text></g>;}
export function StateTransformation({before,after,title}:{before:Vector;after:Vector;title:string}){return <><Stage label={title+': '+stateName(before)+' diventa '+stateName(after)}><text x="450" y="35" textAnchor="middle" className="svg-title">{title}</text>{[before,after].map((v,i)=><g key={i}><text x={i?680:220} y="76" textAnchor="middle" fontSize="21" fill={C.ink}>{i?'Dopo':'Prima'} · {stateName(v)}</text><Polarization v={v} cx={i?565:105} cy={200} r={56}/><Bloch v={v} cx={i?754:294} cy={220} r={83} small/><text x={i?680:220} y="350" textAnchor="middle" fontSize="20" fill={C.blue}>H: {num(probabilityH(v)*100,1)}% · V: {num((1-probabilityH(v))*100,1)}%</text></g>)}<path d="M421 218H475" stroke={C.red} strokeWidth="2" markerEnd="url(#arrow-red)"/><text x="450" y="414" textAnchor="middle" fontSize="18" fill={C.gray}>Le percentuali indicano una eventuale misura H/V in quel punto.</text></Stage><p className="diagram-key">Il disegno piano rappresenta il campo nel piano trasversale alla propagazione; la sfera rappresenta lo stato. I due disegni descrivono la stessa polarizzazione. Le sfere intermedie sono previsioni del simulatore.</p></>;}
export function PairTable({p,counts,last}:{p:number[];counts:number[];last:number}){const n=counts.reduce((a,b)=>a+b,0);return <div className="pair-table-wrap"><table className="pair-grid"><caption>Esiti della stessa prova · probabilità prevista e conteggio osservato</caption><thead><tr><th>Primo / secondo</th><th>A₂</th><th>B₂</th><th>Primo sistema</th></tr></thead><tbody>{[0,1].map(i=><tr key={i}><th>{i?'B₁':'A₁'}</th>{[0,1].map(j=>{const k=2*i+j;return <td key={j} className={last===k?'last-pair':''}><strong>{num(p[k]*100,1)}%</strong><span>{counts[k]||0} coppie</span><small>{['AA','AB','BA','BB'][k]}{last===k?' · ultima prova':''}</small></td>;})}<td><strong>{num((p[2*i]+p[2*i+1])*100,1)}%</strong><span>{(counts[2*i]||0)+(counts[2*i+1]||0)} esiti</span></td></tr>)}<tr><th>Secondo sistema</th>{[0,1].map(i=><td key={i}><strong>{num((p[i]+p[i+2])*100,1)}%</strong><span>{(counts[i]||0)+(counts[i+2]||0)} esiti</span></td>)}<td><strong>100%</strong><span>{n} prove</span></td></tr></tbody></table></div>;}
