"use client";
import {useState} from 'react';
import {Choice,Range,Stage,C,num,TrialButtons,Results,useTrials} from './lab-common';
import {Notebook,Preset,Explain,Reading,PairTable,SlideLink,Toggle} from './lab-notebook';
import {pairDistribution,type PairSource} from '@/lib/quantum-experiments';
import {rad} from '@/lib/physics';
import {PairConstruction} from './pair-construction';
const sources:[string,string][]=[['independent','Due diagonali indipendenti'],['coherent-even','Sovrapposizione HH / VV'],['coherent-odd','Sovrapposizione HV / VH'],['mixed-even','Scelta casuale HH oppure VV'],['mixed-odd','Scelta casuale HV oppure VH']];
export function LabPairsGuided(){
 const [source,setSource]=useState<PairSource>('coherent-even'),[a,setA]=useState(0),[b,setB]=useState(0),[phase,setPhase]=useState(0),[build,setBuild]=useState(false),[interact,setInteract]=useState(true),[swap,setSwap]=useState(false);
 const effective=build?(interact?(swap?'coherent-odd':'coherent-even'):'independent'):source;
 // In the construction, before CNOT the state is D on the first qubit and H on the second.
 const productBefore=[Math.cos(rad(a-45))**2,Math.sin(rad(a-45))**2].flatMap(x=>[x*Math.cos(rad(b))**2,x*Math.sin(rad(b))**2]);
 const p=build&&!interact?productBefore:pairDistribution(effective,a,b,build?0:phase);
 const signature=(build?'Costruzione: interazione '+(interact?'attiva':'esclusa')+', X sul secondo '+(swap?'attiva':'esclusa'):sources.find(x=>x[0]===source)?.[1])+' · misure '+a+'° / '+b+'° · fase '+(build?'0°':source.startsWith('coherent')?phase+'°':'non definita'),trials=useTrials(p,signature);
 const pairPhase=build?0:phase;
 const mixed=pairDistribution(effective.endsWith('odd')?'mixed-odd':'mixed-even',a,b);
 const distinguishable=effective.startsWith('coherent')&&p.some((x,i)=>Math.abs(x-mixed[i])>1e-8);
 const preset=(s:PairSource,angle=0)=>{setBuild(false);setSource(s);setA(angle);setB(angle);setPhase(0);};
 return <Notebook intro={<>Una prova produce due risultati, che vanno conservati insieme. Confronteremo preparazioni con gli stessi conteggi individuali e tabelle delle coppie differenti; cambieremo poi la misura per distinguere una scelta casuale da una sovrapposizione.</>}
 experiments={<><Preset onClick={()=>preset('independent')}>Indipendenti</Preset><Preset onClick={()=>preset('coherent-even')}>Concordi in H/V</Preset><Preset onClick={()=>preset('coherent-odd')}>Discordi in H/V</Preset><Preset onClick={()=>preset('mixed-even',45)}>Miscela sulle diagonali</Preset><Preset onClick={()=>preset('coherent-even',45)}>Sovrapposizione sulle diagonali</Preset><Preset onClick={()=>{setBuild(true);setInteract(false);setSwap(false);setA(0);setB(0);setPhase(0);}}>Costruisci la coppia</Preset><SlideLink page={194}>Correlazione e anticorrelazione nelle slide</SlideLink></>}
 controls={<>{!build?<><Choice label="Sorgente di coppie" value={source} onChange={v=>setSource(v as PairSource)} options={sources}/><Explain>{source==='independent'?'La sorgente prepara separatamente due polarizzazioni +45°. La descrizione di ciascun qubit determina in questo caso anche quella della coppia.':source.startsWith('mixed')?'A ogni prova la sorgente sceglie casualmente una delle due coppie indicate, con probabilità uguali. Conserva questa alternativa nella preparazione; una fase relativa fra le due scelte non è definita.':'La sorgente prepara un unico stato congiunto, con contributi uguali delle due alternative indicate. La fase relativa appartiene alla preparazione della coppia.'}</Explain><Range label="Fase della preparazione congiunta" value={phase} min={-360} max={360} unit="°" onChange={setPhase} disabled={!source.startsWith('coherent')}/><Explain>Modifica la relazione di fase fra le due alternative della sovrapposizione. La misura H/V mantiene le stesse coppie possibili; cambiando la misura si può rendere osservabile la fase. Il controllo è inattivo per le miscele e per la preparazione indipendente.</Explain></>:<><Toggle label="Applica l’interazione controllata" checked={interact} onChange={v=>{setInteract(v);if(!v)setSwap(false);}}>Partiamo da +45° sul primo qubit e H sul secondo. L’interazione lascia H del secondo invariato nel contributo in cui il primo è H; lo scambia con V nel contributo in cui il primo è V. Si ottiene la sovrapposizione HH/VV senza misurare il primo qubit.</Toggle><Toggle label="Scambia H e V sul secondo qubit" checked={swap} disabled={!interact} onChange={setSwap}>Dopo l’interazione, questo scambio locale porta HH in HV e VV in VH. La preparazione diventa anticorrelata nella lettura H/V.</Toggle></>}
 <Range label="Orientazione della misura sul primo" value={a} max={90} unit="°" onChange={setA}/><Explain>A₁ è l’uscita lungo la direzione scelta, B₁ quella perpendicolare. A 0° leggiamo H/V; a 45° leggiamo +45°/−45°.</Explain>
 <Range label="Orientazione della misura sul secondo" value={b} max={90} unit="°" onChange={setB}/><Explain>A₂ e B₂ sono le due uscite del secondo analizzatore. Cambiarne l’orientazione cambia la misura sul secondo sistema; la preparazione alla sorgente rimane quella scelta.</Explain>
 <Reading title="La stessa operazione del laboratorio 6"><p>La lettura sulle diagonali equivale, per queste statistiche, a inserire l’operazione R su ciascun qubit e misurare poi H/V. Le impostazioni a 45° riproducono quindi il confronto dopo ricombinazione delle slide.</p></Reading></>}
 result={<><p>Gli esiti sono concordi nel <strong>{num(100*(p[0]+p[3]),1)}%</strong> delle prove e discordi nel <strong>{num(100*(p[1]+p[2]),1)}%</strong>. I totali ai margini della tabella mostrano ciò che ciascun osservatore può contare da solo.</p><p>Con sorgenti concordi e discordi nella lettura H/V, le frequenze individuali sono entrambe 50/50, mentre le coppie occupano caselle diverse. La concordanza in una sola misura può essere prodotta anche da una miscela. Per la sovrapposizione HH/VV con fase nulla, la misura diagonale distingue la preparazione coerente dalla miscela. La possibilità di distinguerle dipende dalla fase e dalla misura.</p>{effective.startsWith('coherent')&&<p><strong>Con fase {num(pairPhase,0)}° e misure {a}° / {b}°:</strong> {distinguishable?'la distribuzione prevista differisce da quella della miscela delle stesse alternative. Un campione abbastanza numeroso permette di osservare la differenza.':'la distribuzione coincide con quella della miscela delle stesse alternative. Questo confronto non distingue le preparazioni; la coincidenza riguarda soltanto la misura selezionata.'}</p>}</>}
 model={<><p>Si calcolano le quattro probabilità della coppia prima di campionare un evento. Le sovrapposizioni hanno due ampiezze di uguale modulo e fase relativa regolabile; le miscele hanno pesi classici uguali. L’interazione guidata è uno scambio condizionato sul secondo qubit. Le orientazioni degli analizzatori definiscono proiezioni su polarizzazioni lineari ortogonali.</p><p>La preparazione HV/VH è anticorrelata nella base H/V. La sua correlazione in altre basi dipende anche dalla fase: il solo nome «anticorrelata» non implica esiti opposti per qualsiasi misura. Le probabilità locali delle sorgenti congiunte bilanciate restano 50/50. Il confronto dei registri richiede l’associazione degli esiti della stessa prova.</p></>}>
 <Reading title={build?'Dalla preparazione separata alla coppia':'Due analizzatori, una registrazione congiunta'}><p>{build?(interact?(swap?'L’interazione ha preparato HH/VV; lo scambio sul secondo qubit l’ha trasformata in HV/VH.':'L’interazione ha trasformato la preparazione separata in una sovrapposizione HH/VV.'):'Il primo qubit è +45°, il secondo è H. Attiva l’interazione per seguire la formazione della coppia.'):sources.find(x=>x[0]===source)?.[1]+'. La prima lettera di ogni coppia appartiene al primo sistema, la seconda al secondo.'}</p></Reading>
 {build&&<PairConstruction interact={interact} swap={swap}/>}
 <Stage label={'Due analizzatori a '+a+' e '+b+' gradi'}><text x="450" y="44" textAnchor="middle" className="svg-title">La sorgente prepara una nuova coppia a ogni prova</text><rect x="355" y="85" width="190" height="65" rx="8" fill="var(--mq-surface)" stroke={C.blue}/><text x="450" y="125" textAnchor="middle" fontSize="22" fill={C.blue}>Sorgente</text><path d="M355 117L200 233M545 117L700 233" fill="none" stroke={C.blue} strokeWidth="2"/>{[a,b].map((v,i)=>{const x=i?700:200;return <g key={i}><circle cx={x} cy="265" r="65" fill="var(--mq-panel)" stroke={i?C.green:C.blue}/><line x1={x-50*Math.cos(rad(v))} y1={265+50*Math.sin(rad(v))} x2={x+50*Math.cos(rad(v))} y2={265-50*Math.sin(rad(v))} stroke={i?C.green:C.blue} strokeWidth="4"/><text x={x} y="365" textAnchor="middle" fontSize="23" fill={C.ink}>Misura {i+1}: {v}°</text><text x={x} y="412" textAnchor="middle" fontSize="19" fill={C.gray}>A{i+1} lungo l’asse · B{i+1} perpendicolare</text></g>;})}</Stage>
 <TrialButtons {...trials} noun="coppie"/><PairTable p={p} counts={trials.counts} last={trials.last}/>
 <Reading title="Leggere una riga del registro"><p>{trials.last<0?'Esegui una prova per evidenziare la casella corrispondente.':<>L’ultima coppia è <strong>{['AA','AB','BA','BB'][trials.last]}</strong>: aggiorna una sola casella della tabella, una riga del primo sistema e una colonna del secondo.</>} Le somme delle righe danno le frequenze del primo sistema; quelle delle colonne danno le frequenze del secondo. I totali individuali non conservano quale esito accompagnasse l’altro.</p><p>Con «Conserva confronto» puoi mantenere i risultati attuali prima di cambiare sorgente. Per confrontare miscela e sovrapposizione, tieni entrambi gli analizzatori a 45° e la fase della sovrapposizione a 0°.</p></Reading>
 <Results probabilities={p} counts={trials.counts} labels={['AA','AB','BA','BB']} signature={signature}/>
 </Notebook>;
}
