"use client";
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Choice,Results,TrialButtons,Stage,C,num,useTrials} from './lab-common';
import {Notebook,Preset,Explain,Toggle,Reading,SlideLink} from './lab-notebook';
import {amplitudes,initialStates,probabilityH,configuredCircuit,circuitOperation,qubitTrajectory,type CircuitBlock} from '@/lib/quantum-experiments';
import {blochCoordinates,qubitName} from '@/lib/bloch-interaction';
import {type Vector} from '@/lib/physics';
import {AngleControl,CircuitOverview} from './circuit-overview';
import {BlochPoint} from './bloch-point';
import {descriptions,options,gateSymbol,blockSettings,chooseGate,axisFor} from './circuit-operations';
function SumDiagram({v}:{v:Vector}){const [a,b]=amplitudes(v);const k=Math.SQRT1_2;return <Stage label="Contributi delle componenti H e V a ciascuna uscita di R"><defs><marker id="arrow-amber" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill={C.green}/></marker></defs><text x="450" y="42" className="svg-title" textAnchor="middle">Come si combinano i contributi dopo R</text>{[1,-1].map((sign,i)=>{const x=i?670:225,y=250,ax=a[0]*k*140,ay=-a[1]*k*140,bx=b[0]*k*sign*140,by=-b[1]*k*sign*140;return <g key={sign}><text x={x} y="92" textAnchor="middle" fontSize="22" fill={C.ink}>Uscita {i?'1':'0'}</text><circle cx={x} cy={y} r="145" fill="none" stroke={C.line}/><line x1={x} y1={y} x2={x+ax} y2={y+ay} stroke={C.blue} strokeWidth="5" markerEnd="url(#arrow-blue)"/><line x1={x+ax} y1={y+ay} x2={x+ax+bx} y2={y+ay+by} stroke={C.green} strokeWidth="4" strokeDasharray="5 3" markerEnd="url(#arrow-amber)"/><circle cx={x+ax+bx} cy={y+ay+by} r="6" fill={C.red}/><line x1={x} y1={y+8} x2={x+ax+bx} y2={y+ay+by+8} stroke={C.red} strokeWidth="2" markerEnd="url(#arrow-red)"/><text x={x} y="422" textAnchor="middle" fontSize="20" fill={C.red}>Probabilità: {num(((ax+bx)**2+(ay+by)**2)/140**2*100,1)}%</text></g>;})}</Stage>;}
const blockOf=(gate:string,phase=0):CircuitBlock=>({gate,phase,axis:0});
const single=(gate:string,phase=0)=>[blockOf(gate,phase),blockOf('I'),blockOf('I')];
const phaseCircuit=(phase:number)=>[blockOf('H'),blockOf('P',phase),blockOf('H')];
function StateSummary({v}:{v:Vector}){const a=blochCoordinates(v),p=probabilityH(v);return <><strong>{qubitName(v)}</strong><span>0: {num(p*100,1)}% · 1: {num((1-p)*100,1)}%</span><span>{a.hasPhase?'Fase relativa '+num(a.phase,1)+'°':'Fase relativa non definita'}</span></>;}
function OperationView({before,after,block,skipped}:{before:Vector;after:Vector;block:CircuitBlock;skipped:boolean}){return <div className="qubit-transformation"><section><h3>Prima dell’operazione</h3><BlochPoint v={before}/><StateSummary v={before}/></section><div className="qubit-transform-arrow" aria-hidden="true">→</div><section><h3>Dopo {skipped?'il tratto escluso':gateSymbol(block.gate)}</h3><BlochPoint v={after} axis={skipped?undefined:axisFor(block)} path={skipped?undefined:qubitTrajectory(before,block)}/><StateSummary v={after}/></section><p>Il cerchio vuoto indica la posizione iniziale; il punto blu indica quella finale. La curva corallo segue la trasformazione sulla sfera. Le percentuali riguardano una misura 0/1 eseguita in quel punto.</p></div>;}
export function LabCircuitGuided(){
 const controlRef=useRef<HTMLDivElement>(null);
 const [blocks,setBlocks]=useState<CircuitBlock[]>(()=>phaseCircuit(0)),[source,setSource]=useState<Vector>(initialStates.H),[last,setLast]=useState(true),[step,setStep]=useState(3);
 const selectBlock=(n:number)=>{setStep(n);controlRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});controlRef.current?.focus({preventScroll:true});};
 const states=configuredCircuit(blocks,source,last),block=blocks[step-1],gate=block.gate,skipped=step===3&&!last,p=probabilityH(states.at(-1)!),sourceAngles=blochCoordinates(source);
 const signature=qubitName(source)+' · p(0) iniziale '+num(probabilityH(source),4)+(sourceAngles.hasPhase?' · fase iniziale '+num(sourceAngles.phase,3)+'°':'')+' · '+blocks.map((b,i)=>i===2&&!last?'Blocco 3 escluso':gateSymbol(b.gate)+' ['+blockSettings(b)+']').join(' → ');
 const trials=useTrials([p,1-p],JSON.stringify({source,blocks,last}));
 const update=(i:number,b:Partial<CircuitBlock>)=>{setBlocks(all=>all.map((v,k)=>k===i?{...v,...b,axis:0}:v));setStep(i+1);};
 const load=(s:Vector,sequence:CircuitBlock[],selected=1)=>{setSource([...s]);setBlocks(sequence);setLast(true);setStep(selected);};
 const sourceIs=(v:Vector)=>source.every((x,i)=>Math.abs(x-v[i])<1e-8),order=blocks.map(b=>b.gate).join('');
 const examples=gate==='H'?['H','V','D','A']:gate==='Y'?['H','D','C']:gate==='Z'?['H','D','A']:gate==='P'?['D','A','H']:['H','V','D'];
 const unchanged=states[step].every((x,i)=>Math.abs(x-states[step-1][i])<1e-8);
 return <Notebook intro={<>Un circuito è una sequenza di operazioni: ciascun blocco riceve uno stato, lo trasforma e passa il risultato al successivo. Useremo i nomi 0 e 1 per i due esiti della misura, che nella parte sulla polarizzazione erano indicati con H e V. La sequenza R–F–R riprende l’esperimento della lezione: una fase che conserva le probabilità intermedie può cambiare quelle finali. Le operazioni X, Y e Z permettono poi di costruire e confrontare altre sequenze.</>}
 experiments={<><Preset active={order==='HPH'&&blocks[1].phase===0&&sourceIs(initialStates.H)&&last} onClick={()=>load(initialStates.H,phaseCircuit(0),3)}>R–F–R · Fase nulla</Preset><Preset active={order==='HPH'&&blocks[1].phase===180&&sourceIs(initialStates.H)&&last} onClick={()=>load(initialStates.H,phaseCircuit(180),3)}>R–F–R · Mezzo ciclo</Preset><Preset active={order==='HPH'&&!last} onClick={()=>{load(initialStates.H,phaseCircuit(180),2);setLast(false);}}>Misura prima dell’ultima R</Preset><Preset onClick={()=>load(initialStates.H,single('X'))} active={order==='XII'&&sourceIs(initialStates.H)&&last}>X · Da 0 a 1</Preset><Preset onClick={()=>load(initialStates.H,[blockOf('X'),blockOf('X'),blockOf('I')],2)} active={order==='XXI'&&sourceIs(initialStates.H)&&last}>X due volte</Preset><Preset onClick={()=>load(initialStates.D,single('Y'))} active={order==='YII'&&sourceIs(initialStates.D)&&last}>Y · Da + a −</Preset><Preset onClick={()=>load(initialStates.D,[blockOf('Z'),blockOf('H'),blockOf('I')])} active={order==='ZHI'&&sourceIs(initialStates.D)&&last}>Z · Rendi visibile la fase</Preset><Preset onClick={()=>load(initialStates.H,phaseCircuit(-90),2)} active={order==='HPH'&&blocks[1].phase===-90&&sourceIs(initialStates.H)&&last}>F · Prova un angolo negativo</Preset><SlideLink page={180}>Operazioni nella lezione</SlideLink></>}
 overview={<CircuitOverview blocks={blocks} states={states} last={last} selected={step} onSelect={selectBlock} onUpdate={update} onSource={setSource}/>}
 controls={<><div className="selected-block-control" ref={controlRef} tabIndex={-1}><span className="circuit-eyebrow">BLOCCO {step} SELEZIONATO</span><Choice label="Operazione da applicare" value={gate} options={options} onChange={g=>update(step-1,chooseGate(block,g))}/><Explain>Seleziona un blocco del circuito e scegli l’operazione. Gli altri due passaggi mantengono la loro configurazione.</Explain></div>

 {gate==='P'&&<section className="retarder-settings"><AngleControl label="Variazione di fase" value={block.phase} min={-360} max={360} onChange={phase=>update(step-1,{phase})} disabled={skipped}/><Explain>Un angolo positivo e il corrispondente angolo negativo fanno percorrere lo stesso parallelo in versi opposti. Per esempio, +90° seguito da −90° restituisce lo stato iniziale. Puoi digitare il segno meno oppure usare il pulsante ±. A 0° il punto rimane fermo.</Explain><div className="phase-shortcuts">{[-180,-90,0,90,180].map(a=><Button key={a} variant={block.phase===a?'default':'outline'} disabled={skipped} onClick={()=>update(step-1,{phase:a})}>{a>0?'+':''}{a}°</Button>)}</div></section>}
 <div className="applied-setting" aria-live="polite"><strong>{skipped?'Blocco escluso':'Operazione applicata'}</strong><span>{gateSymbol(gate)} · {blockSettings(block)}</span></div>
 <Toggle label="Applica il terzo blocco" checked={last} onChange={setLast}>Escludendolo, la misura riceve direttamente lo stato uscito dal secondo blocco. Puoi così confrontare il risultato prima e dopo l’ultima operazione.</Toggle>
 <Button variant="outline" onClick={()=>{setBlocks(s=>[...s].reverse());setStep(1);}}>Inverti l’ordine dei tre blocchi</Button><Explain>Il primo blocco diventa l’ultimo e l’ultimo diventa il primo. Lo stato iniziale rimane lo stesso. In generale, cambiare l’ordine cambia il risultato.</Explain>
 <Button variant="outline" onClick={()=>load(initialStates.D,[blockOf('X'),blockOf('H'),blockOf('I')])}>Confronta X–R con R–X</Button><Explain>Partendo da +, X lascia lo stato invariato e R lo porta in 0. Invertendo l’ordine si ottiene I–R–X: R porta + in 0 e X porta 0 in 1. La misura finale passa così da 0 certo a 1 certo.</Explain></>}
 result={<><p>Il circuito parte da <strong>{qubitName(source)}</strong> e arriva a <strong>{qubitName(states.at(-1)!)}</strong>. La misura finale prevede <strong>{num(p*100,2)}% di esiti 0</strong> e <strong>{num((1-p)*100,2)}% di esiti 1</strong>.</p><p>Le probabilità si aggiornano quando cambia la preparazione o una delle operazioni. I conteggi si costruiscono avviando le prove; ogni nuova configurazione apre una nuova raccolta.</p>{order==='ZHI'&&sourceIs(initialStates.D)&&<p>Il percorso dell’esempio è + → − → 1 → 1. Z cambia la fase dello stato +, producendo −; R trasforma poi − in 1. Il cambiamento di fase diventa così osservabile nella misura finale.</p>}{order==='HPH'&&<p>{last?'Dopo F, R ricombina le ampiezze: la fase può così modificare le probabilità finali.':'L’ultima R è esclusa. La misura 0/1 riceve direttamente lo stato dopo F, che conserva le probabilità presenti all’ingresso di F.'}</p>}</>}
 model={<><p>Il simulatore descrive uno stato puro mediante due ampiezze, a e b, associate agli esiti 0 e 1. Le probabilità sono i quadrati dei loro moduli. X scambia a e b; Z cambia il segno di b; Y porta la coppia (a, b) in (−ib, ia), dove i indica una rotazione di un quarto di giro nel piano delle ampiezze. Una stessa fase applicata a entrambe le ampiezze non modifica lo stato rappresentato sulla sfera.</p><p>R calcola (a+b)/√2 e (a−b)/√2. F conserva l’ampiezza associata a 0 e ruota quella associata a 1 dell’angolo scelto. La sfera mantiene la rappresentazione geometrica di queste operazioni. I nomi X, Y e Z identificano operazioni fissate; il solo angolo regolabile nel circuito è quello di F.</p><p>Il trascinamento modifica lo stato iniziale e ricalcola tutta la sequenza. Le sfere intermedie sono previsioni del modello; ogni prova genera un esito soltanto alla misura finale, ripartendo ogni volta dalla stessa preparazione. I nomi 0/1 sostituiscono H/V senza modificare il modello matematico.</p></>}>
 <div className="sequence-strip" aria-label="Passaggi da esaminare">{blocks.map((b,i)=><Button variant={step===i+1?'default':'outline'} aria-pressed={step===i+1} key={i} onClick={()=>setStep(i+1)}>{i+1}. {gateSymbol(b.gate)} · {i===2&&!last?'Blocco escluso':descriptions[b.gate].short}</Button>)}</div>
 <Reading title={skipped?'Blocco 3 escluso':descriptions[gate].name}><p>{skipped?'Lo stato uscito dal secondo blocco attraversa questo tratto invariato e arriva alla misura.':descriptions[gate].text}</p><p>In questo passaggio <strong>{qubitName(states[step-1])}</strong> diventa <strong>{qubitName(states[step])}</strong>. {unchanged?'Per lo stato in ingresso scelto, il punto rimane nella stessa posizione.':'La curva sulla sfera mostra come agisce l’operazione sullo stato in ingresso.'}</p></Reading>
 <OperationView before={states[step-1]} after={states[step]} block={block} skipped={skipped}/>
 <Reading title={'Esempi con '+gateSymbol(gate)}><p>La tabella applica soltanto {gateSymbol(gate)} a ciascuno stato iniziale. «Carica» prepara quel caso nel primo blocco e lascia I negli altri due, così puoi raccogliere gli esiti e confrontarli con la previsione.</p></Reading>
 <div className="operation-examples"><table><thead><tr><th>Prima</th><th>Dopo {gateSymbol(gate)}</th><th>Probabilità 0 / 1</th><th>Prova</th></tr></thead><tbody>{examples.map(key=>{const before=initialStates[key],after=circuitOperation(before,block),p0=probabilityH(after);return <tr key={key}><th>{qubitName(before)}</th><td>{qubitName(after)}</td><td>{num(p0*100,1)}% / {num((1-p0)*100,1)}%</td><td><Button variant="outline" onClick={()=>load(before,[{...block},blockOf('I'),blockOf('I')])}>Carica</Button></td></tr>;})}</tbody></table></div>
 <Reading title="Che cosa significano + e −"><p>I due stati occupano punti opposti dell’equatore. Entrambi danno 50/50 nella misura 0/1; la loro fase relativa differisce di mezzo giro. R porta + in 0 e − in 1. Questo esempio mostra perché, per prevedere una sequenza di operazioni, occorre conservare anche la fase dello stato.</p></Reading>
 {gate==='H'&&!skipped&&<><Reading title="Come R ricombina le ampiezze"><p>Ogni ampiezza in ingresso contribuisce a entrambi gli esiti. Per l’esito 0 i contributi si sommano; per l’esito 1 il secondo contributo cambia verso. Le frecce verde e corallo rappresentano questi contributi, mentre la risultante blu determina la probabilità. Con lo stato + i contributi si rinforzano in 0 e si cancellano in 1; con lo stato − avviene il contrario.</p></Reading><SumDiagram v={states[step-1]}/></>}
 <Reading title="Eseguire il circuito"><p>Ogni prova prepara un nuovo qubit nello stato iniziale scelto, applica tutte le operazioni attive e legge 0 oppure 1. Selezionare un passaggio cambia il dettaglio consultato; i conteggi riguardano sempre l’uscita dell’intero circuito.</p></Reading><TrialButtons {...trials}/><Results probabilities={[p,1-p]} counts={trials.counts} labels={['0','1']} signature={signature}/>
 </Notebook>;
}
