"use client";
import {useState} from 'react';
import {Range,Results,TrialButtons,Stage,C,num,useTrials} from './lab-common';
import {Notebook,Preset,Explain,Reading,SlideLink} from './lab-notebook';
import {decoheredPair,environmentCoherence} from '@/lib/quantum-experiments';

export function EnvironmentDiagram({interaction,diagonal}:{interaction:number;diagonal:boolean}){
 const coherence=environmentCoherence(interaction),gap=58*(1-coherence);
 return <Stage label={'Coppia entangled: il secondo sistema interagisce con l’ambiente; intensità '+interaction+' su 100. Entrambi sono poi misurati '+(diagonal?'lungo le diagonali':'in H/V')}>
 <text x="450" y="36" textAnchor="middle" className="svg-title">La stessa coppia, prima e dopo l’interazione</text>
 <rect x="28" y="72" width="172" height="156" rx="15" fill="var(--mq-surface)" stroke={C.red}/><text x="114" y="99" textAnchor="middle" fontSize="19" fill={C.red}>Coppia</text><text x="114" y="124" textAnchor="middle" fontSize="19" fill={C.red}>entangled</text><text x="114" y="155" textAnchor="middle" fontSize="18" fill={C.ink}>HH e VV</text><text x="114" y="180" textAnchor="middle" fontSize="16" fill={C.gray}>con fase definita</text><text x="114" y="210" textAnchor="middle" fontSize="15" fill={C.gray}>Nuova coppia</text>
 {[100,200].map((y,i)=><g key={y}><line x1="200" y1={y} x2="744" y2={y} stroke={C.blue} strokeWidth="3" markerEnd="url(#arrow-blue)"/><text x="237" y={y-14} fontSize="18" fill={C.blue}>Sistema {i+1}</text><rect x="746" y={y-28} width="126" height="57" rx="8" fill="var(--mq-panel)" stroke={C.blue}/><text x="809" y={y+6} textAnchor="middle" fontSize="19" fill={C.blue}>{diagonal?'+45° / −45°':'H / V'}</text></g>)}
 <text x="809" y="60" textAnchor="middle" fontSize="17" fill={C.gray}>Due misure</text>
 <rect x="427" y="174" width="152" height="53" rx="8" fill={interaction?'var(--mq-surface)':'var(--mq-surface)'} stroke={C.green}/><text x="503" y="206" textAnchor="middle" fontSize="18" fill={C.green}>{interaction?'Interazione '+num(interaction,0):'Isolato'}</text>
 <path d="M503 228V280" stroke={interaction?C.green:C.line} strokeWidth="3" strokeDasharray={interaction?undefined:'5 5'}/>
 <rect x="287" y="280" width="451" height="126" rx="14" fill="var(--mq-surface)" stroke="var(--mq-wire)"/><text x="310" y="314" fontSize="21" fill={C.green}>Ambiente</text><text x="310" y="349" fontSize="17" fill={C.ink}>{interaction===0?'Riceve la stessa traccia':interaction===100?'Distingue H da V':'Riceve tracce diverse'}</text><text x="310" y="376" fontSize="16" fill={C.gray}>Non viene misurato</text>
 <circle cx={631-gap/2} cy="340" r="25" fill={C.blue} fillOpacity=".25" stroke={C.blue}/><circle cx={631+gap/2} cy="340" r="25" fill={C.green} fillOpacity=".25" stroke={C.green}/><text x="631" y="391" textAnchor="middle" fontSize="15" fill={C.gray}>Tracce di H e V</text>
 <text x="450" y="440" textAnchor="middle" fontSize="17" fill={C.gray}>Il circuito conserva entrambi i sistemi; i dati dell’ambiente rimangono esclusi dalla lettura.</text>
 </Stage>;
}
export function LabEnvironmentGuided(){
 const [interaction,setInteraction]=useState(0),[diagonal,setDiagonal]=useState(true);
 const coherence=environmentCoherence(interaction),angle=diagonal?45:0,joint=decoheredPair(interaction,angle),reference=decoheredPair(0,angle);
 const labels=diagonal?['++','+−','−+','−−']:['HH','HV','VH','VV'];
 const signature='Coppia HH/VV · interazione '+interaction+'/100 · lettura '+(diagonal?'diagonale':'H/V'),trials=useTrials(joint,signature);
 const same=joint[0]+joint[3],configure=(v:number)=>{setInteraction(v);setDiagonal(true);};
 return <Notebook intro={<>Riprendiamo la coppia entangled del laboratorio precedente, preparata in modo che H e V compaiano con uguale probabilità e che i due esiti siano concordi. Facciamo interagire il secondo sistema con l’ambiente e osserviamo soltanto la coppia. L’ambiente può conservare una traccia diversa a seconda della componente H o V con cui ha interagito: al crescere di questa distinzione, la coppia perde la coerenza iniziale.</>}
 experiments={<><Preset active={interaction===0&&diagonal} onClick={()=>configure(0)}>1. Coppia isolata</Preset><Preset active={interaction===50&&diagonal} onClick={()=>configure(50)}>2. Interazione parziale</Preset><Preset active={interaction===100&&diagonal} onClick={()=>configure(100)}>3. Tracce distinguibili</Preset><SlideLink page={205}>L’ambiente nelle slide</SlideLink></>}
 controls={<><Range label="Accoppiamento con l’ambiente" value={interaction} onChange={setInteraction}/><div className="interaction-ends"><span>Stessa traccia</span><span>Tracce distinguibili</span></div><Explain><p>Questo comando regola quanto le due alternative H e V del secondo sistema lasciano tracce differenti nell’ambiente. A 0 la coppia è isolata. A 100 le tracce sono completamente distinguibili; i valori intermedi descrivono un’interazione parziale.</p><p>La scala da 0 a 100 è una regolazione del modello: al valore 50 l’indicatore di coerenza residua vale circa 71%. Il comando regola l’interazione, mentre l’indicatore sottostante ne quantifica l’effetto. Tutte le coppie arrivano ai rivelatori.</p></Explain><Reading title="Scegliere che cosa misurare"><p>I due analizzatori vengono orientati nello stesso modo. La scelta cambia la domanda posta alla coppia dopo l’interazione.</p><div className="notebook-actions vertical"><Preset active={!diagonal} onClick={()=>setDiagonal(false)}>Misura H / V</Preset><Preset active={diagonal} onClick={()=>setDiagonal(true)}>Misura +45° / −45°</Preset></div><p>H/V distingue orizzontale e verticale. La lettura diagonale distingue le polarizzazioni +45° e −45°, indicate nei conteggi con + e −. Il primo simbolo di ciascun esito riguarda il sistema 1, il secondo il sistema 2.</p></Reading><Reading title="Una sequenza da provare"><p>Il confronto iniziale usa 10.000 prove diagonali sulla coppia isolata. Ripetendo la raccolta con accoppiamento 100 compaiono anche esiti discordi. La lettura H/V, alle stesse condizioni di accoppiamento, conserva invece la concordanza: la differenza fra le due misure permette di riconoscere quale informazione sia divenuta inaccessibile nella descrizione della sola coppia.</p></Reading></>}
 result={<><p>Con l’interazione a <strong>{num(interaction,0)} su 100</strong>, la misura {diagonal?'diagonale':'H/V'} dà esiti concordi nel <strong>{num(same*100,1)}%</strong> delle prove e discordi nel <strong>{num((1-same)*100,1)}%</strong>. Il valore si riferisce alle probabilità; una raccolta finita può discostarsene.</p><p>{interaction===0?'La coppia isolata conserva la fase della preparazione e mostra concordanza perfetta sia in H/V sia sulle diagonali.':interaction===100?'Quando le tracce nell’ambiente sono completamente distinguibili, la sola coppia si comporta come una miscela di HH e VV. In H/V rimane una correlazione perfetta; sulle diagonali i quattro esiti hanno la stessa probabilità.':'Le tracce parzialmente distinguibili riducono la concordanza sulle diagonali. La correlazione H/V resta perfetta, mentre la relazione di fase che consentiva la concordanza diagonale risulta indebolita.'}</p><p>Questa riduzione della coerenza nella descrizione della coppia è la <strong>decoerenza</strong>. Il modello conserva la descrizione quantistica dell’insieme formato dalla coppia e dall’ambiente; osservare soltanto i due sistemi lascia fuori le correlazioni sviluppate con l’ambiente.</p></>}
 model={<><p>La preparazione iniziale è la sovrapposizione coerente ed equiprobabile di HH e VV, con fase relativa nulla. Il secondo qubit interagisce con un ambiente inizialmente puro: H lascia l’ambiente invariato, V ne ruota lo stato di un angolo proporzionale al comando, da 0° a 90°. Quando le due tracce diventano distinguibili, le probabilità della sola coppia si avvicinano a quelle di una scelta casuale fra HH e VV. Il programma calcola le probabilità della coppia sommando su tutti gli esiti dell’ambiente, che qui non viene letto.</p><p>Il modello descrive una perdita di coerenza rispetto alle componenti HH e VV senza assorbimento né rilassamento. L’indicatore riportato vale 1 per tracce identiche e 0 per tracce ortogonali; coincide con il contrasto fra esiti concordi e discordi nella lettura diagonale. L’interazione rappresenta una possibile causa di decoerenza: altre interazioni possono produrre comportamenti differenti.</p><p>Ogni prova usa una nuova coppia e un ambiente preparato nello stesso stato iniziale. Ridurre il comando cambia l’interazione delle prove successive; non ricostruisce lo stato delle coppie già misurate. Con tracce completamente distinguibili, la coppia è una miscela separabile di HH e VV. Le letture mostrate si riferiscono a questa famiglia di stati e non costituiscono una verifica universale dell’entanglement.</p></>}>
 <EnvironmentDiagram interaction={interaction} diagonal={diagonal}/><p className="diagram-key">Le due linee seguono i membri della coppia. Soltanto il secondo incontra l’ambiente, rappresentato dal riquadro corallo. I cerchi indicano in modo qualitativo quanto le due tracce siano distinguibili; la loro area di sovrapposizione non è una scala di probabilità.</p>
 <Reading title="Dove si vede la perdita di coerenza"><p>La misura H/V continua a produrre soltanto HH e VV, anche quando l’ambiente li distingue completamente. La misura diagonale è sensibile alla relazione di fase fra queste alternative: per la coppia isolata i due esiti sono sempre concordi; aumentando l’interazione compaiono +− e −+, fino a rendere i quattro esiti equiprobabili.</p></Reading>
 <div className="environment-comparison"><section className={!diagonal?'active':''}><span className="circuit-eyebrow">LETTURA H / V</span><h3>La correlazione rimane</h3><p>Esiti concordi HH oppure VV</p><div className="before-after"><span>Coppia isolata<strong>100%</strong></span><span>Dopo l’interazione<strong>100%</strong></span></div></section><section className={diagonal?'active':''}><span className="circuit-eyebrow">LETTURA DIAGONALE</span><h3>La coerenza diventa osservabile</h3><p>Esiti concordi ++ oppure −−</p><div className="before-after"><span>Coppia isolata<strong>100%</strong></span><span>Dopo l’interazione<strong>{num((1+coherence)*50,1)}%</strong></span></div></section></div>
 <div className="coherence-indicator"><div><span>Coerenza residua della coppia</span><strong>{num(coherence*100,1)}%</strong></div><div className="coherence-track"><span style={{width:coherence*100+'%'}}/></div><p>È un indicatore del modello, riferito alla relazione fra HH e VV. Al 100% la fase iniziale è interamente disponibile nelle misure della coppia; allo 0% la coppia ha perso questa coerenza. Nella lettura diagonale, l’indicatore è la differenza fra la percentuale di esiti concordi e quella di esiti discordi.</p></div>
 <div className="data-table-wrap environment-table"><table className="data-table"><caption>Le probabilità nella lettura {diagonal?'diagonale':'H/V'} selezionata</caption><thead><tr><th>Esito</th><th>Coppia isolata</th><th>Dopo l’interazione</th></tr></thead><tbody>{labels.map((label,i)=><tr key={label}><th>{label}</th><td>{num(reference[i]*100,1)}%</td><td>{num(joint[i]*100,1)}%</td></tr>)}</tbody></table></div>
 <Reading title="Dalle previsioni ai conteggi"><p>Ogni prova registra entrambi i risultati della stessa coppia. Per esempio, {diagonal?' +− significa +45° sul primo sistema e −45° sul secondo':'HV significa H sul primo sistema e V sul secondo'}. Aumentando il numero di prove, le frequenze tendono ai valori riportati nella colonna «Dopo l’interazione».</p><p>Considerato singolarmente, ciascun sistema continua a dare due esiti equiprobabili in entrambe le letture. Per osservare la variazione occorre conservare l’associazione fra i due risultati e confrontare le coppie.</p></Reading><TrialButtons {...trials} noun="coppie"/><Results probabilities={joint} counts={trials.counts} labels={labels} signature={signature} caption="Conteggi dopo l’interazione"/>
 </Notebook>;
}
