"use client";
import {useEffect,useRef,useState,useId,ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Play,Pause,RotateCcw,Pin,ChevronDown,Download} from 'lucide-react';
import {Vector,randomSource,sample} from '@/lib/physics';
import {wilson,csvDownload} from '@/lib/statistics';
import {LabIntroduction,LabDiscussion} from './lab-reading';
import {ControlNote} from './lab-guidance';
import {toView} from '@/lib/bloch-interaction';
export const C={red:'var(--mq-blue)',blue:'var(--mq-green)',green:'var(--mq-coral)',ink:'var(--mq-text)',gray:'var(--mq-muted)',line:'var(--mq-wire)',pale:'var(--mq-surface)'};
export const num=(n:number,d=1)=>(Math.abs(n)<.5*10**(-d)?0:n).toLocaleString('it-IT',{maximumFractionDigits:d,minimumFractionDigits:d});
export function Range({label,value,min=0,max=100,step=1,unit='',onChange,disabled=false}:{label:string;value:number;min?:number;max?:number;step?:number;unit?:string;onChange:(n:number)=>void;disabled?:boolean}){const id=useId();const root=useRef<HTMLDivElement>(null);useEffect(()=>{const el=root.current?.querySelector('[role="slider"]');el?.setAttribute('aria-labelledby',id);el?.setAttribute('aria-valuetext',num(value,step<1?(String(step).split(".")[1]?.length||1):0)+unit);},[id,value,unit,step]);return <div className="control" ref={root}><div className="control-label"><label id={id}>{label}</label><output>{num(value,step<1?(String(step).split(".")[1]?.length||1):0)}{unit}</output></div><Slider aria-labelledby={id} value={[value]} min={min} max={max} step={step} disabled={disabled} onValueChange={v=>onChange(v[0])}/><div className="range-extents"><span>{min}{unit}</span><span>{max}{unit}</span></div><ControlNote label={label}/></div>;}
export function Choice({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(s:string)=>void}){const id=useId();return <div className="control"><label id={id} className="select-label">{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={id} className="lab-select"><SelectValue placeholder="Scegli una previsione"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o[0]} value={o[0]}>{o[1]}</SelectItem>)}</SelectContent></Select><ControlNote label={label}/></div>;}
export function Segments({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(s:string)=>void}){return <div className="control"><span className="select-label">{label}</span><Tabs value={value} onValueChange={onChange}><TabsList className="lab-segments" aria-label={label}>{options.map(o=><TabsTrigger key={o[0]} value={o[0]}>{o[1]}</TabsTrigger>)}</TabsList></Tabs><ControlNote label={label}/></div>;}
export function LabLayout({children,controls,observation,model,wide=false}:{children:ReactNode;controls:ReactNode;observation:ReactNode;model:ReactNode;wide?:boolean}){return <><LabIntroduction/><nav className="reading-nav" aria-label="All’interno del laboratorio">{[["regolazioni","Regolazioni"],["esperimento","Esperimento"],["lettura-risultato","Lettura dei risultati"]].map(([id,label])=><button key={id} type="button" onClick={()=>{const el=document.getElementById(id);el?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});el?.focus({preventScroll:true});}}>{label}</button>)}</nav><div className={"experiment-layout"+(wide?" experiment-wide":"")}><aside className="control-panel" id="regolazioni" tabIndex={-1}><div className="panel-heading">Regolare l’esperimento</div>{controls}</aside><section className="experiment-surface" id="esperimento" tabIndex={-1}>{children}</section></div><section className="observation" id="lettura-risultato" tabIndex={-1}><span>IL RISULTATO ATTUALE</span><p>{observation}</p></section><LabDiscussion/><details className="model-details"><summary>Il modello e le sue condizioni <ChevronDown size={16}/></summary><div>{model}</div></details></>;}
export function FigureCaption({title,children}:{title:string;children:ReactNode}){return <div className="figure-explanation"><h3>{title}</h3><div>{children}</div></div>;}
export function Stage({children,label,className=''}:{children:ReactNode;label:string;className?:string}){
 const [expanded,setExpanded]=useState(false),dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(expanded)dialog.current?.showModal();else if(dialog.current?.open)dialog.current.close();},[expanded]);
 const drawing=<svg viewBox="0 0 900 450" role="img" aria-label={label}><title>{label}</title><defs><pattern id="fine-grid" width="30" height="30" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".85" fill="var(--mq-surface)"/></pattern><radialGradient id="sphere-light" cx="35%" cy="25%" r="80%"><stop offset="0" stopColor="var(--mq-panel)"/><stop offset=".7" stopColor="var(--mq-surface)"/><stop offset="1" stopColor="var(--mq-surface)"/></radialGradient><marker id="arrow-red" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill={C.red}/></marker><marker id="arrow-blue" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill={C.blue}/></marker></defs><rect width="900" height="450" fill="url(#fine-grid)" opacity=".48"/>{children}</svg>;
 return <div className={'stage '+className}>{!expanded&&drawing}<div className="figure-toolbar"><Button ref={trigger} variant="ghost" onClick={()=>setExpanded(true)}>Ingrandisci figura</Button><span>Il disegno ingrandito conserva gli stessi dati.</span></div><dialog className="figure-dialog" ref={dialog} aria-label={label} onClose={()=>{setExpanded(false);trigger.current?.focus();}}><div className="figure-dialog-heading"><p>{label}</p><Button variant="outline" autoFocus onClick={()=>setExpanded(false)}>Chiudi figura</Button></div>{expanded&&<div className="figure-dialog-drawing">{drawing}</div>}</dialog></div>;
}

export function Bloch({v,cx,cy,r=120,label='',axis,small=false}:{v:Vector;cx:number;cy:number;r?:number;label?:string;axis?:Vector;small?:boolean}){const project=(v:Vector)=>{const u=toView(v);return [cx+r*u[0],cy-r*u[1]];};const [x,y]=project(v);return <g><circle cx={cx} cy={cy} r={r} fill="url(#sphere-light)" stroke="var(--mq-wire)" strokeWidth="1.2"/><ellipse cx={cx} cy={cy} rx={r} ry={r*.28} fill="none" stroke="var(--mq-wire)" strokeDasharray="5 6"/><path d={'M'+(cx-r)+' '+cy+' A'+r+' '+r*.28+' 0 0 0 '+(cx+r)+' '+cy} fill="none" stroke="var(--mq-wire)"/>{[0,1].map(plane=><path key={plane} d={Array.from({length:97},(_,i)=>{const t=i*Math.PI/48;return (i?'L':'M')+project(plane?[Math.cos(t),0,Math.sin(t)]:[0,Math.cos(t),Math.sin(t)]).join(' ');}).join(' ')} fill="none" stroke="var(--mq-wire)" strokeDasharray="4 6"/>)}<line x1={cx} y1={cy-r*.96} x2={cx} y2={cy+r*.96} stroke="var(--mq-wire)"/><line x1={cx-r} y1={cy} x2={cx+r} y2={cy} stroke="var(--mq-wire)"/>{axis&&<line x1={project(axis.map(k=>-k) as Vector)[0]} y1={project(axis.map(k=>-k) as Vector)[1]} x2={project(axis)[0]} y2={project(axis)[1]} stroke={C.green} strokeWidth="2" strokeDasharray="5 4"/>}<circle cx={cx} cy={cy-r*.96} r="3" fill={C.blue}/><circle cx={cx} cy={cy+r*.96} r="3" fill={C.green}/><line x1={cx} y1={cy} x2={x} y2={y} stroke={C.red} strokeWidth="3.5" strokeDasharray={toView(v)[2]<0?"5 3":undefined} markerEnd="url(#arrow-red)"/><circle cx={x} cy={y} r="5" fill={C.red}/><circle cx={cx} cy={cy} r="2.5" fill="var(--mq-muted)"/><text x={cx} y={cy-r-18} textAnchor="middle" fill={C.ink} fontSize={small?17:19}>{label}</text>{!small&&<><text x={cx+12} y={cy-r*.96-8} fill={C.blue} fontSize="15">H</text><text x={cx+12} y={cy+r*.96+10} fill={C.green} fontSize="15">V</text><text x={project([1,0,0])[0]+10} y={project([1,0,0])[1]+5} fill={C.gray} fontSize="14">+45°</text><text x={project([-1,0,0])[0]-10} y={project([-1,0,0])[1]+5} textAnchor="end" fill={C.gray} fontSize="14">−45°</text></>}</g>;}
export function useFrame(running:boolean,callback:(dt:number)=>void){const cb=useRef(callback);cb.current=callback;useEffect(()=>{if(!running)return;let id=0,last=0;const f=(t:number)=>{const dt=last?Math.min((t-last)/1000,.05):0;last=t;if(dt)cb.current(dt);id=requestAnimationFrame(f);};id=requestAnimationFrame(f);return()=>cancelAnimationFrame(id);},[running]);}
export function useTrials(probabilities:number[],signature:string,seed=28183){const [counts,setCounts]=useState(()=>probabilities.map(()=>0)),[last,setLast]=useState(-1);const rng=useRef(randomSource(seed));useEffect(()=>{setCounts(probabilities.map(()=>0));setLast(-1);},[signature]);const run=(n:number)=>{const additions=probabilities.map(()=>0);let outcome=0;for(let i=0;i<n;i++){outcome=sample(probabilities,rng.current);additions[outcome]++;}setCounts(c=>additions.map((v,i)=>(c[i]||0)+v));setLast(outcome);};const reset=()=>{setCounts(probabilities.map(()=>0));setLast(-1);};return {counts,last,run,reset,total:counts.reduce((a,b)=>a+b,0)};}
export function TrialButtons({run,reset,total,noun='prove'}:{run:(n:number)=>void;reset:()=>void;total:number;noun?:string}){
 const [auto,setAuto]=useState(false),[rate,setRate]=useState(2000),buffer=useRef(0);useEffect(()=>{if(total===0){setAuto(false);buffer.current=0;}},[total]);useFrame(auto,dt=>{buffer.current+=dt*rate;const n=Math.floor(buffer.current);if(n){run(n);buffer.current-=n;}});
 return <><div className="experiment-actions"><div className="button-cluster"><Button onClick={()=>run(1)}><Play size={14}/> Una prova</Button><Button variant="outline" onClick={()=>run(100)}>+100</Button><Button variant="outline" onClick={()=>run(1000)}>+1.000</Button><Button variant="outline" onClick={()=>run(10000)}>+10.000</Button><Button variant="outline" onClick={()=>run(100000)}>+100.000</Button></div><span className="trial-total">{total.toLocaleString('it-IT')} {noun}</span><Button variant="ghost" size="icon" aria-label="Azzera i conteggi" onClick={()=>{setAuto(false);reset();}}><RotateCcw/></Button></div><div className="continuous-controls"><Button variant="outline" onClick={()=>setAuto(v=>!v)}>{auto?<Pause size={15}/>:<Play size={15}/>} {auto?'Pausa raccolta':'Raccolta continua'}</Button><Range label="Prove al secondo" value={rate} min={100} max={10000} step={100} onChange={setRate}/></div></>;
}
export function Results({probabilities,counts,labels=['A','B'],signature,caption='Esiti della misura',explain=true}:{probabilities:number[];counts:number[];labels?:string[];signature:string;caption?:string;explain?:boolean}){
 const [pin,setPin]=useState<{counts:number[];p:number[];signature:string;labels:string[]}|null>(null),total=counts.reduce((a,b)=>a+b,0);
 const exportData=()=>csvDownload('quantum-lab-conteggi.csv',[["Configurazione","Esito","Conteggio","N","Probabilita","Frequenza","Wilson_95_min","Wilson_95_max"],...labels.map((l,i)=>[signature,l,counts[i]||0,total,probabilities[i],total?counts[i]/total:'',...wilson(counts[i]||0,total)])]);
 return <div className="results"><div className="result-heading"><h3>{caption}</h3><div className="result-actions"><Button variant="ghost" disabled={!total} onClick={exportData}><Download size={14}/> Esporta conteggi</Button><Button variant="ghost" className="pin-button" disabled={!total&&!pin} onClick={()=>setPin(pin?null:{counts:[...counts],p:[...probabilities],signature,labels:[...labels]})}><Pin size={14}/>{pin?'Rimuovi confronto':'Conserva confronto'}</Button></div></div>
 {explain&&<p className="result-reading">La barra colorata mostra la parte della raccolta in cui è comparso ciascun esito: una barra piena corrisponde al 100%. Il segno verticale indica la probabilità prevista dal modello, anche prima di raccogliere dati.</p>}
 <div className="probability-row result-columns" aria-hidden="true"><span>Esito</span><span>Frequenza nella raccolta</span><span>Conteggi</span><span>Previsione</span></div>
 <div className="probability-bars">{probabilities.map((p,i)=>{const k=counts[i]||0;return <div className="probability-row" key={labels[i]}><span className="outcome-label">{labels[i]}</span><div className="bar-track" role="img" aria-label={labels[i]+': '+(total?num(100*k/total,1)+'% nella raccolta':'nessuna prova')+'; previsione '+num(p*100,1)+'%'}><div className={'bar-fill series-'+i} style={{width:(total?k/total:0)*100+'%'}}/><span className="theory-marker" style={{left:p*100+'%'}}/></div><span className="outcome-count">{k.toLocaleString('it-IT')}</span><span className="outcome-prob">{num(p*100,1)}%</span></div>;})}</div>
 <p className="sampling-note">{total?<>Per l’esito {labels[0]} sono stati registrati {counts[0].toLocaleString('it-IT')} eventi su {total.toLocaleString('it-IT')}: {counts[0].toLocaleString('it-IT')} ÷ {total.toLocaleString('it-IT')} × 100 = <strong>{num(100*counts[0]/total,1)}%</strong>. Questa è la frequenza osservata. Ripetendo la raccolta può cambiare, mentre la probabilità prevista rimane {num(100*probabilities[0],1)}% finché preparazione e misura restano le stesse.</>:<>Non sono ancora state eseguite prove. Le barre sono vuote; i segni verticali e le percentuali riportano già ciò che il modello prevede.</>}</p>
 {explain&&<p className="sampling-note">Ogni prova ripete l’esperimento con una nuova preparazione. Modificare la preparazione o la misura avvia una nuova raccolta: conserva prima il confronto se vuoi ricordare i conteggi precedenti.</p>}
 {pin&&<div className="saved-comparison"><strong>Raccolta conservata</strong><span>{pin.signature}</span><div>{pin.labels.map((l,i)=><span key={l}>{l}: {pin.counts[i].toLocaleString('it-IT')} eventi su {pin.counts.reduce((a,b)=>a+b,0).toLocaleString('it-IT')} · previsione {num(pin.p[i]*100,1)}%</span>)}</div></div>}
 {total>0&&<details className="statistical-detail"><summary>Approfondimento: la precisione di una raccolta</summary><p>Un numero finito di prove fornisce una stima della probabilità. La tabella aggiunge, per ciascun esito, un intervallo calcolato dai suoi conteggi. Se ripetessimo molte raccolte indipendenti della stessa dimensione e costruissimo ogni volta l’intervallo, il procedimento è progettato per includere la probabilità reale in circa 95 casi su 100. Questa proprietà riguarda il procedimento ripetuto; non assegna una probabilità al valore fisso del modello. L’effettiva copertura può differire dal 95%, soprattutto con pochi eventi.</p><p>Qui si usa il metodo di Wilson. Per probabilità intermedie, raccolte più numerose danno in genere intervalli più stretti. Il nome del metodo e gli intervalli sono riportati anche nel file esportato; il confronto principale fra barre e previsione può essere letto senza questo approfondimento.</p><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Esito</th><th>Limite inferiore</th><th>Limite superiore</th></tr></thead><tbody>{labels.map((l,i)=>{const [a,b]=wilson(counts[i]||0,total);return <tr key={l}><td>{l}</td><td>{num(a*100,2)}%</td><td>{num(b*100,2)}%</td></tr>;})}</tbody></table></div></details>}
 </div>;
}
export function RunButton({running,onClick,label='Avvia'}:{running:boolean;onClick:()=>void;label?:string}){return <Button onClick={onClick}>{running?<Pause/>:<Play/>}{running?'Pausa':label}</Button>;}
export function SmallStat({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="small-stat"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
