"use client";
import {useMemo,useRef,useState,useEffect} from 'react';
import {canvasColor} from '@/lib/theme';
import {Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {C,num,Range,Segments} from './lab-common';
import {randomSource,type Particle} from '@/lib/physics';
export function downloadRows(filename:string,rows:(string|number)[][]){const quote=(x:string|number)=>'"'+String(x).replace(/"/g,'""')+'"',blob=new Blob(['\ufeff'+rows.map(row=>row.map(quote).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function CurvePlot({title,xLabel,yLabel,curves,xMin=0,xMax=90,yMin=0,yMax=1,selected,selectedLabel='Configurazione attuale',children}:{title:string;xLabel:string;yLabel:string;curves:{name:string;color:string;values:number[];xValues?:number[]}[];xMin?:number;xMax?:number;yMin?:number;yMax?:number;selected?:number;selectedLabel?:string;children?:React.ReactNode}){
 const percent=yMin===0&&yMax===1;
 const X=(v:number)=>60+(v-xMin)/(xMax-xMin)*710,Y=(v:number)=>207-(v-yMin)/(yMax-yMin)*152;
 return <section className="analysis-block"><h3>{title}</h3><div className="plot-scroll"><svg viewBox="0 0 840 260" role="img" aria-label={title+'. '+xLabel+'; '+yLabel}><text x="60" y="24" fill={C.gray} fontSize="15">{yLabel}</text>{[0,.25,.5,.75,1].map(t=><g key={t}><line x1="60" x2="770" y1={Y(yMin+t*(yMax-yMin))} y2={Y(yMin+t*(yMax-yMin))} stroke={C.line}/><text x="46" y={Y(yMin+t*(yMax-yMin))+5} textAnchor="end" fill={C.gray} fontSize="14">{percent?num(100*(yMin+t*(yMax-yMin)),0)+'%':num(yMin+t*(yMax-yMin),2)}</text><text x={60+t*710} y="230" textAnchor="middle" fill={C.gray} fontSize="14">{num(xMin+t*(xMax-xMin),1)}</text></g>)}{selected!==undefined&&<line x1={X(selected)} x2={X(selected)} y1="50" y2="207" stroke={C.red} strokeDasharray="5 5"/>}{curves.map((c,k)=><path key={c.name} d={c.values.map((v,i)=>(i?'L':'M')+X(c.xValues?.[i]??(xMin+(xMax-xMin)*i/Math.max(1,c.values.length-1)))+' '+Y(v)).join(' ')} stroke={c.color} strokeWidth="2.8" strokeDasharray={k?'6 4':undefined} fill="none"/>)}<text x="770" y="256" textAnchor="end" fill={C.gray} fontSize="14">{xLabel}</text></svg></div><div className="plot-legend">{curves.map((c,i)=><span key={c.name}><i style={{borderTopColor:c.color,borderTopStyle:i?'dashed':'solid'}}/>{c.name}</span>)}{selected!==undefined&&<span><i className="legend-selected" style={{borderLeftColor:C.red}}/>{selectedLabel}</span>}</div>{children&&<div className="analysis-note">{children}</div>}</section>;
}
export function ParticleCanvas({particles,width=720,height=340,radius=1,label,color=C.blue,heat=false,arrows=false,highlight=false}:{particles:Particle[];width?:number;height?:number;radius?:number;label:string;color?:string;heat?:boolean;arrows?:boolean;highlight?:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;const paint=canvasColor(color,el);ctx.clearRect(0,0,width,height);ctx.fillStyle=canvasColor('var(--mq-panel)',el);ctx.fillRect(0,0,width,height);ctx.fillStyle=canvasColor('var(--mq-surface)',el);ctx.fillRect(0,0,width/2,height);
  if(heat){const bins=new Array(32).fill(0);for(const p of particles)bins[Math.min(31,Math.max(0,Math.floor(p.x/width*8)+8*Math.floor(p.y/height*4)))]++;const max=Math.max(1,2*particles.length/32);bins.forEach((v,i)=>{ctx.fillStyle=`rgba(${parseInt(paint.slice(1,3),16)},${parseInt(paint.slice(3,5),16)},${parseInt(paint.slice(5,7),16)},${.08+.8*Math.min(1,v/max)})`;ctx.fillRect((i%8)*width/8,Math.floor(i/8)*height/4,width/8-1,height/4-1);});}
  else{ctx.fillStyle=paint;ctx.beginPath();const r=Math.max(.85,radius);for(const p of particles){ctx.moveTo(p.x+r,p.y);ctx.arc(p.x,p.y,r,0,Math.PI*2);}ctx.fill();if(arrows){ctx.strokeStyle=paint;ctx.lineWidth=.8;ctx.beginPath();for(let i=0;i<particles.length;i+=Math.max(1,Math.ceil(particles.length/160))){const p=particles[i];ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+p.vx*.12,p.y+p.vy*.12);}ctx.stroke();}}
  ctx.setLineDash([6,6]);ctx.strokeStyle=canvasColor('var(--mq-wire)',el);ctx.beginPath();ctx.moveTo(width/2,0);ctx.lineTo(width/2,height);ctx.stroke();ctx.setLineDash([]);if(highlight&&particles[0]){const p=particles[0];ctx.strokeStyle=canvasColor(C.red,el);ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.stroke();}
 });
 return <figure className="particle-figure"><figcaption>{label}</figcaption><canvas ref={canvas} width={width} height={height} role="img" aria-label={label+'; '+particles.length.toLocaleString('it-IT')+' particelle'}>Distribuzione di {particles.length} particelle. Le statistiche numeriche sono riportate sotto la figura.</canvas></figure>;
}
export function MotionEnsemble({x0,v,dv,t}:{x0:number;v:number;dv:number;t:number}){
 const [n,setN]=useState('5000'),[dx,setDx]=useState(1),[seed,setSeed]=useState(4781),[zoom,setZoom]=useState(false);const samples=useMemo(()=>{const rng=randomSource(seed);return Array.from({length:+n},()=>[2*rng()-1,2*rng()-1]);},[n,seed]);
 const support=Math.max(.1,dx+dv*t),center=x0+v*t;
 const left=zoom?center-support:x0-dx+Math.min(0,(v-dv)*8)-1,right=zoom?center+support:x0+dx+Math.max(0,(v+dv)*8)+1,bins=new Array(81).fill(0);
 for(const [a,b] of samples){const position=center+dx*a+dv*b*t;bins[Math.max(0,Math.min(80,Math.floor((position-left)/(right-left)*81)))]++;}
 const vals=bins.map(x=>x/+n),max=Math.max(.05,...vals);return <section className="analysis-block"><h3>Molte preparazioni, una distribuzione di posizioni</h3><div className="inline-controls"><Segments label="Particelle indipendenti" value={n} options={[["1000","1.000"],["5000","5.000"],["20000","20.000"]]} onChange={setN}/><Range label="Incertezza iniziale sulla posizione" value={dx} max={5} step={.1} unit=" m" onChange={setDx}/></div><div className="notebook-actions"><Button variant="outline" onClick={()=>setSeed(s=>s+1)}>Nuovo campione iniziale</Button><Button variant="outline" aria-pressed={zoom} onClick={()=>setZoom(z=>!z)}>{zoom?"Usa scala fissa nel tempo":"Ingrandisci la distribuzione"}</Button></div><div className="plot-scroll"><svg viewBox="0 0 840 210" role="img" aria-label={'Istogramma di '+n+' posizioni al tempo '+num(t)}>{[0,.5,1].map(k=><g key={k}><line x1="60" x2="770" y1={150-k*115} y2={150-k*115} stroke={C.line}/><text x="49" y={155-k*115} textAnchor="end" fill={C.gray} fontSize="14">{num(100*max*k,0)}%</text></g>)}{vals.map((y,i)=><rect key={i} x={60+i*710/81} y={150-y/max*115} width={710/81-.5} height={y/max*115} fill={C.blue} opacity=".72"/>)}<line x1="60" x2="770" y1="150" y2="150" stroke={C.line}/>{[-1,0,1].map(k=><text key={k} x={415+k*355} y="177" fill={C.gray} textAnchor="middle" fontSize="15">{num(left+(k+1)/2*(right-left),1)} m</text>)}<text x="60" y="23" fontSize="15" fill={C.gray}>Frequenze osservate</text></svg></div><div className="analysis-note"><p>Ogni barra conta le particelle che si trovano in un piccolo intervallo di posizioni all’istante attuale. La sua altezza è una percentuale della raccolta: 5% significa 5 particelle ogni 100. L’asse orizzontale riporta le posizioni in metri. {zoom?"L’ingrandimento segue la distribuzione: la larghezza in metri si legge agli estremi dell’asse.":"La scala orizzontale resta fissa durante gli otto secondi del moto, rendendo visibile l’allargamento della distribuzione."} Ogni particella conserva la propria posizione e velocità iniziali mentre scorre il tempo; «Nuovo campione iniziale» estrae un altro insieme di preparazioni.</p><p>Il programma sceglie le posizioni iniziali fra {num(x0-dx,1)} e {num(x0+dx,1)} m e le velocità fra {num(v-dv,1)} e {num(v+dv,1)} m/s. Dentro ciascun intervallo ogni porzione di uguale ampiezza ha la stessa probabilità; la scelta della posizione non influenza quella della velocità. Questa regola costruisce le ripetizioni della preparazione.</p><p>Dopo {num(t,1)} s, gli estremi possibili si calcolano direttamente: {num(x0-dx,1)} + ({num(v-dv,1)}) × {num(t,1)} = <strong>{num(center-dx-dv*t,2)} m</strong> e {num(x0+dx,1)} + ({num(v+dv,1)}) × {num(t,1)} = <strong>{num(center+dx+dv*t,2)} m</strong>. Il disegno principale mantiene una posizione iniziale unica; soltanto questo istogramma considera anche la sua incertezza.</p></div></section>;
}
export function ExportSeries({filename,rows}:{filename:string;rows:(string|number)[][]}){return <Button variant="outline" onClick={()=>downloadRows(filename,rows)}><Download size={15}/> Esporta dati</Button>;}
