"use client";
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Range,Results,TrialButtons,C,num,useTrials,Stage} from './lab-common';
import {Notebook,Preset,Explain,Toggle,Reading,SlideLink,ProbabilityMeter} from './lab-notebook';
import {CurvePlot,downloadRows} from './lab-tools';
import {diagnosticDistribution} from '@/lib/quantum-experiments';
import {randomSource,sample} from '@/lib/physics';
type RecordRow={stabilize:boolean;undo:boolean;phase:number;n:number;a:number[];b:number[]};
function DiagnosisCircuit({phase,stabilize,undo}:{phase:number;stabilize:boolean;undo:boolean}) {
 return <><Stage label="Disposizione comune ai due apparati: preparazione, due cammini, regolazione della fase, possibile interazione e compensazione, ricombinazione, misura">
 <text x="450" y="36" textAnchor="middle" className="svg-title">La disposizione comune ai due apparati</text>
 <circle cx="65" cy="200" r="11" fill={C.red}/><text x="65" y="241" textAnchor="middle" fontSize="17" fill={C.gray}>Sorgente</text><path d="M80 200H166M220 200V115H690V200M220 200V285H690V200M745 200H777V135H840M777 200V265H840" fill="none" stroke={C.blue} strokeWidth="2.5"/>
 {[190,717].map((x,i)=><g key={x}><rect x={x-28} y="169" width="56" height="62" rx="8" fill="var(--mq-surface)" stroke={C.red}/><text x={x} y="208" textAnchor="middle" fontSize="25" fill={C.red}>R</text><text x={x} y="330" textAnchor="middle" fontSize="17" fill={C.gray}>{i?'Ricombina':'Prepara i cammini'}</text></g>)}
 <rect x="330" y="88" width="155" height="54" rx="8" fill="var(--mq-surface)" stroke={C.blue}/><text x="407" y="122" textAnchor="middle" fontSize="20" fill={C.blue}>F · {phase}°</text><text x="407" y="70" textAnchor="middle" fontSize="17" fill={C.gray}>{stabilize?'Fase stabilizzata':'Stabilizzazione esclusa'}</text>
 <rect x="313" y="258" width="139" height="54" rx="8" fill="var(--mq-surface)" stroke={C.green}/><text x="382" y="291" textAnchor="middle" fontSize="17" fill={C.green}>Interazione</text><rect x="496" y="258" width="143" height="54" rx="8" fill={undo?'var(--mq-surface)':'var(--mq-panel)'} stroke={C.green} strokeDasharray={undo?undefined:'5 4'}/><text x="567" y="291" textAnchor="middle" fontSize="17" fill={C.green}>Compensazione</text>
 <text x="477" y="356" textAnchor="middle" fontSize="17" fill={C.gray}>Lettura dell’ambiente: H oppure V, se richiesta</text><path d="M383 313V370H568V313" fill="none" stroke={C.green} strokeDasharray="5 4"/>
 {[135,265].map((y,i)=><g key={y}><circle cx="842" cy={y} r="23" fill="var(--mq-panel)" stroke={C.blue}/><text x="842" y={y+6} textAnchor="middle" fontSize="20" fill={C.blue}>D{i+1}</text></g>)}
 <text x="450" y="416" textAnchor="middle" fontSize="17" fill={C.gray}>I comandi agiscono prima della ricombinazione e della misura finale.</text>
 </Stage><p className="diagram-key">R prepara i due cammini; F ne regola la fase relativa. Il riquadro inferiore indica dove un cammino può lasciare una traccia nell’ambiente e dove viene applicata l’operazione inversa. In assenza di marcatura, la compensazione lascia lo stato invariato. D₁ e D₂ registrano un solo esito a ogni prova.</p></>;
}
export function LabDiagnosis(){
 const [phase,setPhase]=useState(0),[stabilize,setStabilize]=useState(false),[undo,setUndo]=useState(false),[read,setRead]=useState(false);
 const [rows,setRows]=useState<RecordRow[]>([]);
 const [scan,setScan]=useState<{a:number[];b:number[]}|null>(null);
 const a=diagnosticDistribution('phase',phase,stabilize,undo),b=diagnosticDistribution('marker',phase,stabilize,undo),p=a[0]+a[1],q=b[0]+b[1];
 const signature='Fase '+phase+'° · stabilizzazione '+(stabilize?'attiva':'esclusa')+' · compensazione '+(undo?'attiva':'esclusa');
 const t1=useTrials(a,signature,9851),t2=useTrials(b,signature,3547),rng=useRef(randomSource(11742));
 const configure=(s:boolean,u:boolean)=>{setStabilize(s);setUndo(u);setPhase(0);setScan(null);};
 const change=(s:boolean,u:boolean)=>{setStabilize(s);setUndo(u);setScan(null);};
 function scanning(){setScan({a:Array.from({length:13},(_,i)=>{const pp=diagnosticDistribution('phase',i*30,stabilize,undo);let n=0;for(let j=0;j<2000;j++)if(sample(pp,rng.current)<2)n++;return n/2000;}),b:Array.from({length:13},(_,i)=>{const pp=diagnosticDistribution('marker',i*30,stabilize,undo);let n=0;for(let j=0;j<2000;j++)if(sample(pp,rng.current)<2)n++;return n/2000;})});}
 function record(){setRows(s=>[...s,{phase,stabilize,undo,n:t1.total,a:[...t1.counts],b:[...t2.counts]}]);}
 const interpretation=stabilize&&!undo?'La probabilità dipende dalla fase soltanto nell’apparato 1.':!stabilize&&undo?'La probabilità dipende dalla fase soltanto nell’apparato 2.':stabilize&&undo?'Entrambi gli apparati recuperano una dipendenza dalla fase.':'Entrambi gli apparati prevedono 50/50 per ogni fase nominale.';

 return <Notebook
 intro={<>Due apparati producono inizialmente gli stessi conteggi D₁/D₂ per qualunque fase impostata. Vogliamo verificare se questa osservazione basti a descriverne il funzionamento. Sono disponibili due interventi: stabilizzare la fase fra le prove e compensare un’eventuale traccia dei cammini nell’ambiente. Confrontandone gli effetti potremo distinguere le spiegazioni considerate nel modello.</>}
 experiments={<><Preset onClick={()=>configure(false,false)}>Condizioni iniziali</Preset><Preset onClick={()=>configure(true,false)}>Stabilizza soltanto la fase</Preset><Preset onClick={()=>configure(false,true)}>Compensa soltanto la traccia</Preset><Preset onClick={()=>configure(true,true)}>Applica entrambi gli interventi</Preset><SlideLink page={211}>Il confronto nelle slide</SlideLink></>}
 controls={<><Range label="Fase nominale dell’interferometro" value={phase} min={-360} max={360} unit="°" onChange={setPhase}/><Explain>È la differenza di fase impostata fra i due cammini. La scansione ripete la raccolta a tredici valori, da 0° a 360°, per verificare come cambia la probabilità di D₁.</Explain>
 <Toggle label="Stabilizza la fase fra le prove" checked={stabilize} onChange={v=>change(v,undo)}>Rende ripetibile la fase impostata, eliminando le sue eventuali variazioni casuali da una preparazione alla successiva. Agisce sul ritardo relativo; una traccia già presente nell’ambiente resta disponibile.</Toggle>
 <Toggle label="Compensa la traccia dei cammini" checked={undo} onChange={v=>change(stabilize,v)}>Applica l’inversa dell’interazione di marcatura presente nell’apparato, prima dell’ultima R. Se i cammini avevano lasciato tracce diverse, questa operazione le riporta allo stesso stato. Le eventuali variazioni casuali della fase rimangono.</Toggle>
 <Toggle label="Mostra anche la polarizzazione dell’ambiente" checked={read} onChange={setRead}>Suddivide gli stessi eventi secondo la lettura H/V della traccia: D₁·H, D₁·V, D₂·H, D₂·V. Il comando cambia il raggruppamento del registro; i totali D₁/D₂ restano gli stessi. Qui la polarizzazione realizza l’ambiente controllabile incontrato nel laboratorio 08.</Toggle>
 <Button variant="outline" disabled={!t1.total} onClick={record}>Conserva il confronto nel quaderno</Button><Explain>Registra impostazioni e conteggi delle prove a fase fissata. La scansione completa si esporta dal proprio grafico.</Explain>
 </>}
 result={<><p><strong>{interpretation}</strong></p><p>Nell’apparato 1, le variazioni casuali della fase cancellano le frange della raccolta complessiva. Nell’apparato 2, i cammini lasciano tracce distinguibili nell’ambiente. Stabilizzare la fase interviene sulla prima causa; compensare la marcatura interviene sulla seconda. Le curve permettono di seguire separatamente questi effetti, nelle condizioni ideali qui specificate.</p></>}
 model={<><p>Apparato 1: interferometro bilanciato senza marcatura, con un ritardo aggiuntivo uniforme su un ciclo completo e indipendente a ogni prova. Per ciascun valore fissato del ritardo è definita una distribuzione con interferenza. Mediando le distribuzioni relative ai diversi ritardi si ottiene probabilità 1/2 in ciascuna uscita. La stabilizzazione elimina questo ritardo aggiuntivo.</p><p>Apparato 2: fase stabile e marcatura completa, con H associato al primo cammino e V al secondo. La compensazione applica l’inversa dell’interazione prima della ricombinazione. Sono modelli ideali specificati, con raccolte indipendenti nei due apparati; l’esperimento verifica le loro previsioni senza fornire una procedura universale per riconoscere ogni possibile ambiente.</p></>}
 >
 <DiagnosisCircuit phase={phase} stabilize={stabilize} undo={undo}/>
 <div className="diagnostic-apparatus">{[p,q].map((v,i)=><section key={i}><span className="apparatus-number">APPARATO {i+1}</span><h3>{i?'Tracce dei cammini':'Variazioni di fase'}</h3><ProbabilityMeter label="Probabilità di D₁ alla fase selezionata" p={v}/><p>La lettura riguarda {phase}°. La scansione permette di verificare se questa probabilità varia quando cambia la fase.</p></section>)}</div>
 <Reading title="Confrontare gli stessi interventi"><p>Una prima scansione senza interventi fornisce il riferimento. Stabilizzando soltanto la fase e ripetendo la scansione si osserva quale apparato risponde al controllo del ritardo. Il confronto successivo, eseguito con la sola compensazione, verifica il ruolo della traccia nell’ambiente. I pulsanti degli esempi impostano questi casi; i comandi consentono di combinarli liberamente.</p></Reading>
 <TrialButtons run={n=>{t1.run(n);t2.run(n);}} reset={()=>{t1.reset();t2.reset();}} total={t1.total} noun="prove per apparato"/>
 <Results probabilities={read?a:[p,1-p]} counts={read?t1.counts:[t1.counts[0]+t1.counts[1],t1.counts[2]+t1.counts[3]]} labels={read?['D₁·H','D₁·V','D₂·H','D₂·V']:['D₁','D₂']} signature={'Apparato 1 · '+signature+' · lettura '+(read?'congiunta':'D₁/D₂')} caption="Apparato 1 · risultati"/>
 <Results explain={false} probabilities={read?b:[q,1-q]} counts={read?t2.counts:[t2.counts[0]+t2.counts[1],t2.counts[2]+t2.counts[3]]} labels={read?['D₁·H','D₁·V','D₂·H','D₂·V']:['D₁','D₂']} signature={'Apparato 2 · '+signature+' · lettura '+(read?'congiunta':'D₁/D₂')} caption="Apparato 2 · risultati"/>
 <Reading title="Una scansione completa"><p>Si raccolgono 2.000 nuove prove a ciascuna delle tredici fasi: 26.000 prove per apparato, 52.000 complessive. I conteggi a fase fissata, mostrati sopra, costituiscono raccolte separate. Nelle curve la coordinata orizzontale è la fase, quella verticale è la frequenza di D₁.</p><Button onClick={scanning}>Scansiona · 26.000 prove per apparato</Button></Reading>
 {scan&&<><CurvePlot title="Frequenze registrate durante la scansione" xLabel="Fase nominale (gradi)" yLabel="Frequenza di D₁" xMax={360} selected={(phase%360+360)%360} curves={[{name:'Apparato 1',color:C.blue,values:scan.a},{name:'Apparato 2',color:C.green,values:scan.b}]}><p>{interpretation} Le oscillazioni sistematiche vanno distinte dalle piccole irregolarità dovute al campione finito.</p></CurvePlot><div className="notebook-actions"><Button variant="outline" onClick={()=>downloadRows('diagnosi-scansione.csv',[['Fase','N_per_apparato','Frequenza_D1_apparato1','Frequenza_D1_apparato2','Stabilizzazione','Compensazione'],...scan.a.map((v,i)=>[i*30,2000,v,scan.b[i],Number(stabilize),Number(undo)])])}>Esporta la scansione</Button></div></>}
 <Reading title="Quaderno dei confronti">{rows.length?<><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Interventi applicati</th><th>Fase</th><th>N per apparato</th><th>D₁ · apparato 1</th><th>D₁ · apparato 2</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>Stabilizzazione {r.stabilize?'sì':'no'}; compensazione {r.undo?'sì':'no'}</td><td>{r.phase}°</td><td>{r.n}</td><td>{num(100*(r.a[0]+r.a[1])/r.n,1)}%</td><td>{num(100*(r.b[0]+r.b[1])/r.n,1)}%</td></tr>)}</tbody></table></div><div className="notebook-actions"><Button variant="outline" onClick={()=>downloadRows('diagnosi-quaderno.csv',[['Prova','Fase','Stabilizzazione','Compensazione','N','D1H_1','D1V_1','D2H_1','D2V_1','D1H_2','D1V_2','D2H_2','D2V_2'],...rows.map((r,i)=>[i+1,r.phase,Number(r.stabilize),Number(r.undo),r.n,...r.a,...r.b])])}>Esporta il quaderno</Button><Button variant="ghost" onClick={()=>setRows([])}>Svuota il quaderno</Button></div></>:<p>Il quaderno conserverà i confronti registrati con il comando accanto alle regolazioni. Per mantenerli anche dopo l’uscita dal laboratorio, esporta il file CSV.</p>}</Reading>
 </Notebook>;
}
