"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {RotateCcw,Download} from 'lucide-react';
import {LabLayout,FigureCaption,Stage,Bloch,Range,Choice,Segments,Results,TrialButtons,useTrials,useFrame,C,num,RunButton,SmallStat} from '@/components/lab-common';
import {polarVector,rad,TAU,Vector,circuit,pairProbabilities,environmentProbabilities} from '@/lib/physics';
import {blochCoordinates} from '@/lib/bloch-interaction';
import {AngleControl} from './circuit-controls';
import {CurvePlot,MotionEnsemble,downloadRows} from '@/components/lab-tools';
export function LabPolar(){
 const [alpha,setAlpha]=useState(45),[beta,setBeta]=useState(0),[delta,setDelta]=useState(0),[animate,setAnimate]=useState(false),[cycle,setCycle]=useState(0);useFrame(animate,dt=>setCycle(t=>(t+dt*2)%TAU));const state:Vector=[Math.sin(2*rad(alpha))*Math.cos(rad(delta)),Math.sin(2*rad(alpha))*Math.sin(rad(delta)),Math.cos(2*rad(alpha))];const probability=(b:number)=>Math.max(0,Math.min(1,(1+state[0]*Math.sin(2*rad(b))+state[2]*Math.cos(2*rad(b)))/2));const coordinates=blochCoordinates(state),known=([['0',[0,0,1]],['90',[0,0,-1]],['45',[1,0,0]],['-45',[-1,0,0]]] as [string,Vector][]).find(([,v])=>v.every((x,i)=>Math.abs(x-state[i])<1e-8))?.[0]??'';const p=probability(beta),signature='Preparazione '+alpha+'° · Analizzatore '+beta+'° · fase aggiunta '+delta+'° · fase relativa '+(coordinates.hasPhase?num(coordinates.phase,2)+'°':'non definita');const trials=useTrials([p,1-p],signature);
 const line=(cx:number,cy:number,a:number,r:number)=>({x1:cx-r*Math.cos(rad(a)),y1:cy+r*Math.sin(rad(a)),x2:cx+r*Math.cos(rad(a)),y2:cy-r*Math.sin(rad(a))});
 return <LabLayout controls={<><Segments label="Preparazioni note" value={known} options={[["0","H"],["90","V"],["45","+45°"],["-45","−45°"]]} onChange={v=>{setAlpha(+v);setDelta(0);}}/><Range label="Orientazione prima dello sfasamento" value={alpha} min={-90} max={90} unit="°" onChange={setAlpha}/><Range label="Orientazione dell’analizzatore" value={beta} max={180} unit="°" onChange={setBeta}/><AngleControl label="Fase aggiunta alla componente V" value={delta} min={-360} max={360} disabled={!coordinates.hasPhase} onChange={setDelta}/><p className="control-explanation">Il comando aggiunge una fase alla polarizzazione lineare scelta. La diagonale −45° parte già con componenti opposte; la lettura dello stato riporta la fase effettiva dopo questa aggiunta.</p><div className="control-actions"><Button variant="outline" onClick={()=>{setAlpha(45);setDelta(90);}}>Preparazione circolare</Button><Button variant="outline" onClick={()=>{setAlpha(45);setDelta(0);}}>Diagonale lineare</Button></div><div className="control-tip">Prepara prima +45°, poi −45°. Confronta gli esiti con l’analizzatore a 0° e a 45°.</div></>} observation={<>Con l’analizzatore a {beta}°, la probabilità dell’uscita A è <strong>{num(100*p,1)}%</strong>. Quando entrambe le componenti sono presenti, la fase relativa può modificare la figura del campo e il punto sulla sfera. Una preparazione circolare assegna 50/50 a ogni analizzatore lineare.</>} model={<><p>Ogni prova impiega un nuovo pacchetto di luce nella stessa preparazione. L’analizzatore ideale registra un solo esito, A oppure B, senza perdite. Il modello considera qui misure lungo due polarizzazioni lineari perpendicolari.</p><p>La sfera riassume la preparazione attraverso un punto. I suoi poli sono H e V; le diagonali occupano punti opposti dell’equatore. La scomposizione in componenti H e V e lo sfasamento fra esse determinano il punto rappresentato. La spiegazione geometrica accompagna le figure; le relazioni usate dal programma sono documentate nei sorgenti.</p></>}>
 <div className="state-reading" aria-live="polite"><strong>{coordinates.hasPhase?'Fase relativa dello stato: '+num(coordinates.phase,1)+'°':'Una componente è assente: fase relativa non definita'}</strong><span>L’angolo {alpha}° orienta la polarizzazione iniziale nel piano; la fase individua la posizione lungo il parallelo della sfera.</span></div><div className="figure-heading"><span>PREPARAZIONE E MISURA</span><span className="figure-tag">Luce polarizzata</span></div><Stage label={'Polarizzazione '+alpha+' gradi; analizzatore '+beta+' gradi; sfera di Bloch dello stato preparato'}>
 <text x="75" y="69" className="svg-title">Il campo elettrico</text><text x="155" y="137" textAnchor="middle" fontSize="15" fill={C.gray}>Vista lungo il fascio</text><text x="635" y="69" className="svg-title">Lo stato del qubit</text><line x1="513" x2="513" y1="90" y2="364" stroke={C.line}/>
 <line x1="82" y1="244" x2="425" y2="244" stroke="var(--mq-wire)" strokeWidth="2"/><circle cx="155" cy="244" r="75" fill="var(--mq-surface)" stroke="var(--mq-wire)"/><line x1="83" y1="244" x2="227" y2="244" stroke="var(--mq-wire)" strokeDasharray="4 5"/><line x1="155" y1="172" x2="155" y2="316" stroke="var(--mq-wire)" strokeDasharray="4 5"/><path d={Array.from({length:129},(_,i)=>{const q=TAU*i/128;return (i?'L':'M')+(155+70*Math.cos(rad(alpha))*Math.cos(q))+' '+(244-70*Math.sin(rad(alpha))*Math.cos(q-rad(delta)));}).join(' ')} stroke={C.blue} strokeWidth="3" fill="none"/><line x1="155" y1="244" x2={155+70*Math.cos(rad(alpha))*Math.cos(cycle)} y2={244-70*Math.sin(rad(alpha))*Math.cos(cycle-rad(delta))} stroke={C.red} strokeWidth="2"/><circle cx={155+70*Math.cos(rad(alpha))*Math.cos(cycle)} cy={244-70*Math.sin(rad(alpha))*Math.cos(cycle-rad(delta))} r="5" fill={C.red}/><text x="236" y="249" fill={C.blue} fontSize="15">H</text><text x="166" y="168" fill={C.green} fontSize="15">V</text><text x="155" y="349" textAnchor="middle" fill={C.blue} fontSize="19">{alpha}° prima della fase</text>
 <rect x="277" y="183" width="48" height="120" rx="7" fill="var(--mq-panel)" stroke={C.green} strokeWidth="2"/><line {...line(301,243,beta,21)} stroke={C.green} strokeWidth="3"/><text x="301" y="159" textAnchor="middle" fill={C.gray} fontSize="16">Analizzatore</text><text x="301" y="349" textAnchor="middle" fill={C.green} fontSize="19">{beta}°</text>
 <path d="M325 244H371V173H430M371 244V309H430" fill="none" stroke="var(--mq-wire)" strokeWidth="2"/>{[0,1].map((i)=><g key={i}><rect x="420" y={153+i*136} width="44" height="40" rx="7" fill={trials.last===i?(i===0?C.blue:C.green):'var(--mq-surface)'} stroke={i===0?C.blue:C.green}/><text x="442" y={179+i*136} textAnchor="middle" fill={trials.last===i?'var(--mq-on-accent)':C.ink} fontSize="18">{i===0?'A':'B'}</text></g>)}
 <Bloch v={state} axis={polarVector(beta)} cx={706} cy={238} r={118}/><text x="706" y="400" textAnchor="middle" fontSize="15" fill={C.gray}>Blu: stato · asse tratteggiato: misura</text>
 </Stage><div className="experiment-actions"><RunButton running={animate} label="Anima il campo" onClick={()=>setAnimate(a=>!a)}/><span className="trial-total">L’animazione segue un ciclo del campo; preparazione e probabilità restano fisse.</span></div><FigureCaption title="Il campo, la preparazione e le due uscite"><p>Il segmento o l’ellisse a sinistra descrive il movimento della punta del campo elettrico durante un ciclo, guardando il fascio lungo la propagazione. La figura resta in un piano perpendicolare al fascio. L’analizzatore separa due polarizzazioni perpendicolari: A segue l’orientazione scelta, B quella a 90° rispetto ad A.</p><p>Sulla sfera il punto blu rappresenta la preparazione; l’asse tratteggiato indica la misura. Sono due rappresentazioni diverse: il punto sulla sfera non oscilla insieme al campo. Con l’analizzatore a 0°, i poli H e V danno uscite certe, mentre ogni punto dell’equatore dà 50% e 50%.</p><p>Con le impostazioni attuali, il modello prevede <strong>{num(100*p,1)}% in A</strong> e <strong>{num(100*(1-p),1)}% in B</strong>. {Math.abs(state[1])<1e-9?'Il campo è lineare: la sua punta percorre il segmento disegnato.':'La fase può far percorrere alla punta del campo un’ellisse. La forma disegnata dipende anche dalle ampiezze delle due componenti.'} Ogni prova registra un solo evento; le percentuali si stimano ripetendo la preparazione.</p></FigureCaption><TrialButtons {...trials}/><Results probabilities={[p,1-p]} counts={trials.counts} signature={signature} labels={['A','B']}/><CurvePlot title="La stessa preparazione, tutte le orientazioni di misura" xLabel="Orientazione dell’analizzatore (gradi)" yLabel="Probabilità dell’uscita A" xMax={180} selected={beta} curves={[{name:"Preparazione attuale",color:C.blue,values:Array.from({length:181},(_,i)=>probability(i))},{name:"Preparazione nel punto opposto della sfera",color:C.green,values:Array.from({length:181},(_,i)=>1-probability(i))}]}><p>La curva continua segue la preparazione attuale mentre ruotiamo soltanto l’analizzatore. La curva tratteggiata mostra il confronto con la preparazione nel punto opposto della sfera; per esempio, a +45° corrisponde −45°. A una stessa orientazione, le due probabilità di A sommano al 100%. Se una vale 80%, l’altra vale 20%. La linea verticale blu indica l’orientazione attualmente scelta.</p><p>Quando le curve si incontrano al 50%, quella misura non distingue le due preparazioni. Dove una raggiunge il 100% e l’altra lo 0%, le distingue con certezza nel modello ideale. Per le preparazioni circolari entrambe rimangono al 50% con tutti gli analizzatori lineari qui disponibili.</p></CurvePlot></LabLayout>;
}

export function LabMotion(){
 const [x0,setX0]=useState(0),[va,setVa]=useState(3),[vb,setVb]=useState(6),[dv,setDv]=useState(.5),[time,setTime]=useState(0),[running,setRunning]=useState(false);
 const reset=()=>{setTime(0);setRunning(false);};const change=(f:(v:number)=>void)=>(v:number)=>{f(v);reset();};useFrame(running,dt=>setTime(t=>{if(t+dt>=8){setRunning(false);return 8;}return t+dt;}));
 const xa=x0+va*time,xb=x0+vb*time;const sx=(x:number)=>120+(x+60)*4.5;const sy=(x:number)=>390-(x+60)*.75;
 return <LabLayout controls={<><Range label="Posizione iniziale" value={x0} min={-10} max={10} unit=" m" onChange={change(setX0)}/><Range label="Velocità A" value={va} min={-3} max={8} step={.5} unit=" m/s" onChange={change(setVa)}/><Range label="Velocità B" value={vb} min={-3} max={8} step={.5} unit=" m/s" onChange={change(setVb)}/><Range label="Incertezza sulla velocità A" value={dv} max={2} step={.1} unit=" m/s" onChange={change(setDv)}/><div className="control-tip">Imposta velocità uguali, poi cambiane una. La fascia azzurra raccoglie le posizioni compatibili con l’incertezza assegnata.</div></>} observation={<>Dopo {num(time)} s, A si trova a <strong>{num(xa)} m</strong> e B a <strong>{num(xb)} m</strong>. La stessa posizione iniziale è compatibile con moti diversi. L’incertezza sulla velocità amplia l’intervallo delle posizioni previste nel tempo.</>} model={<p>Le particelle si muovono lungo una retta senza cambiare velocità e senza interagire. La posizione finale si ottiene aggiungendo alla posizione iniziale lo spostamento: velocità moltiplicata per tempo. La fascia comprende tutte le posizioni compatibili con l’intervallo di velocità; da sola non assegna frequenze ai valori al suo interno. Il tempo è espresso in secondi e le posizioni in metri.</p>}>
 <div className="figure-heading"><span>STESSA POSIZIONE, DUE MOTI</span><span className="figure-tag">Moto uniforme</span></div><Stage label={'Due moti uniformi. Tempo '+num(time)+' secondi. A a '+num(xa)+' metri, B a '+num(xb)+' metri.'}>
 {[0,1].map(i=><g key={i}><text x="58" y={94+i*95} fontSize="20" fill={i===0?C.blue:C.green}>{i===0?'A':'B'}</text><line x1="116" y1={87+i*95} x2="840" y2={87+i*95} stroke={C.line} strokeWidth="2"/>{[-60,-20,20,60,100].map(x=><g key={x}><line x1={sx(x)} y1={81+i*95} x2={sx(x)} y2={94+i*95} stroke="var(--mq-wire)"/><text x={sx(x)} y={114+i*95} textAnchor="middle" fontSize="14" fill={C.gray}>{x}</text></g>)}<circle cx={sx(x0)} cy={87+i*95} r="8" fill="var(--mq-panel)" stroke={i===0?C.blue:C.green} strokeDasharray="3 3"/><line x1={sx(x0)} y1={87+i*95} x2={sx(i===0?xa:xb)} y2={87+i*95} stroke={i===0?C.blue:C.green} strokeWidth="3" opacity=".3"/>{i===0&&<rect x={sx(xa-dv*time)} y="68" width={dv*time*9} height="38" rx="6" fill={C.blue} opacity=".12"/>}<circle cx={sx(i===0?xa:xb)} cy={87+i*95} r="10" fill={i===0?C.blue:C.green}/><line x1={sx(i===0?xa:xb)} y1={87+i*95} x2={sx(i===0?xa:xb)+(i===0?va:vb)*5} y2={87+i*95} stroke={i===0?C.blue:C.green} strokeWidth="2" markerEnd="url(#arrow-blue)"/></g>)}<text x="837" y="227" textAnchor="end" fontSize="14" fill={C.gray}>Posizione (m)</text>
 <text x="65" y="255" fontSize="15" fill={C.gray}>Posizione nel tempo</text>{[-40,20,80].map(x=><g key={x}><line x1="150" y1={sy(x)} x2="795" y2={sy(x)} stroke={C.line}/><text x="131" y={sy(x)+5} textAnchor="end" fill={C.gray} fontSize="13">{x}</text></g>)}{[0,2,4,6,8].map(t=><text key={t} x={150+t*80} y="414" textAnchor="middle" fill={C.gray} fontSize="14">{t}</text>)}<text x="838" y="414" fill={C.gray} fontSize="14">t (s)</text><path d={'M150 '+sy(x0)+' L'+(150+time*80)+' '+sy(xa-dv*time)+' L'+(150+time*80)+' '+sy(xa+dv*time)+'Z'} fill={C.blue} opacity=".12"/><line x1="150" y1={sy(x0)} x2={150+time*80} y2={sy(xa)} stroke={C.blue} strokeWidth="3"/><line x1="150" y1={sy(x0)} x2={150+time*80} y2={sy(xb)} stroke={C.green} strokeWidth="3" strokeDasharray="7 4"/>
 </Stage><FigureCaption title="Due moti e la loro rappresentazione nel tempo"><p>Le due righe superiori mostrano A in verde e B in corallo sullo stesso asse delle posizioni. Il cerchio vuoto indica il punto di partenza; il punto pieno la posizione all’istante attuale. Il segmento che parte dal punto indica il verso del moto e cresce con la velocità.</p><p>Nel grafico sotto, l’asse orizzontale misura il tempo e quello verticale la posizione in metri. Ogni punto della retta descrive quindi una posizione a un certo istante, non una curva percorsa nello spazio. La fascia azzurra indica l’intervallo consentito dall’incertezza sulla velocità di A. Cambiare un dato iniziale riporta l’esperimento al tempo zero.</p></FigureCaption><div className="experiment-actions"><RunButton running={running} label={time>=8?'Ripeti':'Avvia'} onClick={()=>{if(time>=8)setTime(0);setRunning(!running);}}/><Button variant="outline" onClick={()=>{setRunning(false);setTime(t=>Math.min(8,t+.5));}}>Un passo · 0,5 s</Button><Button variant="ghost" size="icon" aria-label="Riparti dal tempo zero" onClick={reset}><RotateCcw/></Button><span className="trial-total">t = {num(time)} s</span></div><div className="stats-strip"><SmallStat label="Posizione A" value={num(xa)+' m'}/><SmallStat label="Posizione B" value={num(xb)+' m'}/><SmallStat label="Distanza fra le previsioni" value={num(Math.abs(xa-xb))+' m'}/></div><MotionEnsemble x0={x0} v={va} dv={dv} t={time}/></LabLayout>;
}

export function LabWaves(){
 const [phase,setPhase]=useState(0),[amp,setAmp]=useState(1),[running,setRunning]=useState(false),[time,setTime]=useState(0),[pin,setPin]=useState<{phase:number;amp:number}|null>(null);useFrame(running,dt=>setTime(t=>t+dt));
 const intensity=1+amp*amp+2*amp*Math.cos(rad(phase));const path=(kind:number,y:number)=>Array.from({length:251},(_,i)=>{const t=i/250,ph=TAU*(3*t-time*.4),v=kind===0?Math.sin(ph):kind===1?amp*Math.sin(ph+rad(phase)):Math.sin(ph)+amp*Math.sin(ph+rad(phase));return (i?'L':'M')+(140+t*680)+' '+(y-v*30);}).join(' ');
 return <LabLayout controls={<><Range label="Ritardo relativo" value={phase} min={-360} max={360} unit="°" onChange={setPhase}/><Segments label="Confronti" value={String(phase)} options={[["0","Insieme"],["90","¼ di ciclo"],["180","½ ciclo"]]} onChange={v=>setPhase(+v)}/><Range label="Ampiezza dell’onda B" value={amp} max={1.5} step={.1} onChange={setAmp}/><div className="control-actions"><Button variant="outline" onClick={()=>setPin(pin?null:{phase,amp})}>{pin?'Rimuovi confronto':'Conserva configurazione'}</Button></div><div className="control-tip">Con ampiezze uguali, confronta un ritardo nullo, un quarto di ciclo e mezzo ciclo.</div></>} observation={<>L’intensità della somma vale <strong>{num(intensity,2)}</strong> volte quella della sola onda A. {intensity<.001?'Le due oscillazioni si cancellano.':'La fase relativa modifica il risultato anche quando le intensità dei singoli contributi rimangono fisse.'}</>} model={<p>Le due onde hanno la stessa forma periodica, lo stesso periodo e la stessa direzione di oscillazione. Il campo risultante è la somma dei campi in ogni punto. L’intensità, calcolata sull’intera oscillazione, è proporzionale al quadrato dell’ampiezza risultante. L’onda A fornisce l’unità di confronto. L’animazione serve a seguire le oscillazioni; avviarla o fermarla non modifica le intensità previste.</p>}>
 <div className="figure-heading"><span>SOVRAPPOSIZIONE DEI CAMPI</span><span className="figure-tag">Stessa frequenza</span></div><Stage label={'Due onde e la loro somma; ritardo '+phase+' gradi; intensità '+num(intensity,2)}>
 {[0,1,2].map((k)=><g key={k}><text x="54" y={88+k*128} fontSize="18" fill={[C.blue,C.green,C.red][k]}>{['A','B','A + B'][k]}</text><line x1="136" y1={83+k*128} x2="833" y2={83+k*128} stroke={C.line}/><path d={path(k,83+k*128)} fill="none" stroke={[C.blue,C.green,C.red][k]} strokeWidth={k===2?3.5:2.6}/></g>)}<text x="835" y="424" textAnchor="end" fontSize="14" fill={C.gray}>Posizione lungo la propagazione · unità arbitrarie</text>
 </Stage><FigureCaption title="Leggere la somma nello stesso istante"><p>Le tre linee orizzontali segnano il livello di equilibrio. Sopra ogni linea il contributo è positivo, sotto è negativo. In una stessa posizione si somma il valore verde a quello corallo: il risultato forma la curva blu. Le tre curve usano la stessa scala verticale, così il raddoppio e la cancellazione dell’ampiezza sono visibili direttamente.</p><p>{phase===0?'I cicli delle due onde sono allineati: creste e valli coincidono.':phase===180?'Le onde sono separate da mezzo ciclo: le creste di una coincidono con le valli dell’altra.':<>Il ritardo attuale è {num(phase/360,2)} cicli: le due onde occupano momenti diversi della stessa oscillazione.</>} {amp===0?'L’ampiezza B è nulla e rimane soltanto l’onda A.':<>L’ampiezza B vale {num(amp,1)} rispetto all’ampiezza 1 di A.</>}</p></FigureCaption><div className="experiment-actions"><RunButton running={running} label="Anima le onde" onClick={()=>setRunning(v=>!v)}/><span className="trial-total">Ritardo: {num(phase/360,2)} cicli</span></div><div className="stats-strip"><SmallStat label="Intensità di A" value="1,00"/><SmallStat label="Intensità di B" value={num(amp*amp,2)}/><SmallStat label="Intensità della somma" value={num(intensity,2)} detail="Unità: intensità della sola onda A"/></div>{pin&&<div className="notice">Configurazione conservata: ritardo = {pin.phase}°, ampiezza B = {num(pin.amp)}; intensità = {num(1+pin.amp**2+2*pin.amp*Math.cos(rad(pin.phase)),2)}.</div>}<section className="analysis-block"><h3>La somma delle ampiezze nel piano</h3><div className="plot-scroll"><svg viewBox="0 0 840 350" role="img" aria-label="Ampiezze sommate testa a coda e risultante alla stessa scala">
 <defs>{[["wave-a",C.blue],["wave-b",C.green],["wave-sum",C.red]].map(([id,color])=><marker key={id} id={id} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10Z" fill={color}/></marker>)}</defs>
 <text x="55" y="27" fontSize="16" fill={C.gray}>Contributi testa a coda</text><line x1="80" x2="350" y1="107" y2="107" stroke={C.line}/><line x1="160" x2="160" y1="35" y2="178" stroke={C.line}/>
 <line x1="160" y1="107" x2="210" y2="107" stroke={C.blue} strokeWidth="6" markerEnd="url(#wave-a)"/><line x1="210" y1="107" x2={210+50*amp*Math.cos(rad(phase))} y2={107-50*amp*Math.sin(rad(phase))} stroke={C.green} strokeWidth="3" markerEnd={amp>0?'url(#wave-b)':undefined}/><circle cx="160" cy="107" r="3" fill={C.ink}/>
 <text x="405" y="76" fill={C.blue} fontSize="17">A: lunghezza 1</text><text x="405" y="111" fill={C.green} fontSize="17">B: lunghezza {num(amp,1)}, dalla punta di A</text><text x="405" y="149" fill={C.gray} fontSize="16">L’angolo fra i contributi è {phase}°.</text>
 <line x1="55" x2="790" y1="187" y2="187" stroke={C.line}/><text x="55" y="216" fill={C.gray} fontSize="16">Somma, alla stessa scala</text><line x1="80" x2="350" y1="253" y2="253" stroke={C.line}/><circle cx="160" cy="253" r="3" fill={C.ink}/><line x1="160" y1="253" x2={210+50*amp*Math.cos(rad(phase))} y2={253-50*amp*Math.sin(rad(phase))} stroke={C.red} strokeWidth="3" markerEnd={intensity>.00001?'url(#wave-sum)':undefined}/><circle cx={210+50*amp*Math.cos(rad(phase))} cy={253-50*amp*Math.sin(rad(phase))} r="3" fill={C.red}/>
 <text x="405" y="244" fill={C.red} fontSize="17">Lunghezza risultante: {num(Math.sqrt(Math.max(0,intensity)),2)}</text><text x="405" y="282" fill={C.gray} fontSize="16">Intensità risultante: {num(intensity,2)}</text>
 </svg></div><p className="analysis-note">La prima freccia parte dall’origine. La seconda viene spostata, senza cambiarne lunghezza o orientazione, fino alla punta della prima. La somma va dall’origine al punto finale della costruzione. La riportiamo in blu nella riga inferiore, senza cambiarne lunghezza o orientazione, così rimane leggibile anche quando le frecce si sovrappongono. Il piano delle frecce descrive ampiezza e fase: la loro orientazione non indica una direzione del moto nello spazio.</p><p className="analysis-note">L’intensità si ottiene moltiplicando la lunghezza risultante per sé stessa. Con due contributi uguali e allineati la lunghezza è 2 e l’intensità 2 × 2 = 4; con contributi uguali e opposti entrambe sono nulle.</p></section><CurvePlot title="Dalla fase all’intensità" xLabel="Fase relativa (gradi)" yLabel="Intensità rispetto alla sola onda A" xMax={360} yMax={Math.max(4,(1+amp)**2)} selected={(phase%360+360)%360} curves={[{name:"Somma dei campi con fase mantenuta",color:C.red,values:Array.from({length:181},(_,i)=>1+amp*amp+2*amp*Math.cos(rad(2*i)))},{name:"Somma delle sole intensità",color:C.gray,values:new Array(181).fill(1+amp*amp)}]}><p>La curva continua mostra l’intensità prevista per tutti i ritardi, mantenendo fisse le ampiezze. La linea verticale indica il ritardo selezionato. La linea orizzontale tratteggiata somma invece le intensità delle onde separate: qui 1 + {num(amp*amp,2)} = {num(1+amp*amp,2)}. Resta costante perché ignora la relazione fra i cicli.</p><p>Per le ampiezze attuali, la massima intensità si ottiene allineando i contributi: ({num(1,1)} + {num(amp,1)}) × ({num(1,1)} + {num(amp,1)}) = {num((1+amp)**2,2)}. Il minimo è {num((1-amp)**2,2)} e si ottiene opponendoli. Solo contributi di uguale ampiezza si cancellano completamente.</p></CurvePlot></LabLayout>;
}

