const bridges=[
 'Per prevedere il moto abbiamo dovuto conservare posizione e velocità. Quando il sistema contiene migliaia di particelle, possiamo ancora seguire questi dati, oppure limitarci a contare quante particelle occupano una regione. Il gas permette di confrontare le due descrizioni e di verificare che cosa occorra per ricostruire il moto iniziale.',
 'Nel gas abbiamo distinto le informazioni sulle singole particelle dalla distribuzione nello spazio. La simulazione di un’onda richiede una descrizione diversa: occorre conoscere come oscilla il campo. Il prossimo esperimento esamina quali dati servano per sommare due oscillazioni.',
 'La sovrapposizione ha mostrato che la fase modifica il risultato anche quando i contributi separati mantengono la stessa intensità. Nelle fenditure useremo una previsione d’interferenza per generare singoli eventi, verificando come la distribuzione emerga da una raccolta numerosa.',
 'Il programma ha generato posizioni sullo schermo a partire dalle probabilità previste. Con la polarizzazione concentreremo l’attenzione su una misura con due sole uscite, per riconoscere quali informazioni distinguano preparazioni che producono gli stessi conteggi.',
 'Le due diagonali producono gli stessi conteggi H/V, pur occupando punti distinti sulla sfera. Un’operazione che le porta ai poli rende osservabile questa differenza. Il circuito permetterà di seguire come una successione di trasformazioni utilizzi la fase conservata nello stato.',
 'Il circuito ha richiesto una descrizione sufficiente a prevedere tutte le operazioni sul singolo qubit. Per due qubit diventa necessario chiedersi se le descrizioni individuali bastino anche a prevedere quali risultati compariranno insieme.',
 'Le statistiche dei singoli sistemi hanno lasciato indeterminate le correlazioni della coppia. Quando uno dei due interagisce con un ambiente, la descrizione congiunta si estende ulteriormente: esamineremo quali previsioni restino disponibili osservando soltanto la coppia.',
 'L’interazione con l’ambiente ha mostrato come la descrizione di una parte del sistema possa perdere informazioni necessarie ad alcune previsioni. Nel prossimo laboratorio controlleremo esplicitamente quali dati conservare quando interrompiamo e riavviamo una simulazione.',
 'Un archivio è sufficiente rispetto alle operazioni che dovranno seguire. Anche una raccolta di risultati sperimentali lascia aperte più descrizioni possibili: l’ultimo laboratorio confronta interventi che permettono di distinguere due modelli con gli stessi conteggi iniziali.',
 'Il percorso ha messo alla prova le informazioni conservate dal simulatore: condizioni iniziali, distribuzioni, ampiezze, fase e correlazioni. Per discutere un risultato, possiamo ora precisare quale preparazione è stata usata, quale intervento è stato applicato e quali dati sono stati effettivamente osservati.'
];
export function LearningBridge({chapter}:{chapter:number}){return <aside className="learning-bridge"><p>{bridges[chapter]}</p></aside>;}
