export type DemoInfo={id:string;title:string;short:string;part:number;pages:number[];intro:string;bridge:string};
export const parts=['Vettori e trasformazioni','Probabilità e dati','Stati e misura'];
export const chapterTwo:DemoInfo[]=[
{id:'complessi',title:'Numeri complessi nel piano',short:'Numeri complessi',part:0,pages:[8],intro:'Per conservare modulo e fase di un’ampiezza occorrono due numeri reali. Il piano complesso permette di seguirli insieme: la posizione della punta descrive il numero, mentre la freccia ne rende visibili modulo e argomento.',bridge:'Raccogliendo più ampiezze otteniamo un vettore. Dobbiamo ora precisare rispetto a quali direzioni ne scriviamo le componenti.'},
{id:'basi',title:'Vettori, basi e coordinate',short:'Basi e coordinate',part:0,pages:[19],intro:'Un vettore può essere ricostruito come combinazione dei vettori di una base. Le coordinate indicano quanto contribuisce ciascuna direzione; quando la base cambia, la ricostruzione deve restituire lo stesso vettore.',bridge:'Le basi ortogonali consentono di ricavare ogni componente attraverso una proiezione. Il prodotto interno dà una forma algebrica a questa costruzione.'},
{id:'proiezioni',title:'Prodotto interno e ortogonalità',short:'Proiezioni e Gram–Schmidt',part:0,pages:[28],intro:'La proiezione individua la parte di un vettore lungo una direzione assegnata. Sottraendola rimane una componente ortogonale, che permette di costruire nuovi assi a partire da vettori indipendenti.',bridge:'Possiamo ora seguire una trasformazione attraverso l’effetto che produce sui vettori di una base.'},
{id:'matrici',title:'Matrici, nucleo e immagine',short:'Matrici e trasformazioni',part:0,pages:[41,84],intro:'Le colonne di una matrice sono le immagini dei vettori della base canonica. Poiché la trasformazione è lineare, queste immagini determinano il destino di ogni punto della griglia.',bridge:'Fra le matrici che trasformano vettori, alcune conservano prodotti interni e norme. L’aggiunto consente di esprimere queste proprietà.'},
{id:'aggiunto',title:'Aggiunto, hermitiane e unitarie',short:'Aggiunto e conservazione',part:0,pages:[51],intro:'Nel prodotto interno complesso il primo vettore viene coniugato. L’aggiunto è l’operatore che permette di trasferire una matrice da un argomento all’altro del prodotto interno, conservandone il valore.',bridge:'Le matrici hermitiane possiedono autovalori reali e una base ortonormale di autovettori. Questa base rende particolarmente semplice il calcolo.'},
{id:'spettro',title:'Autovettori e decomposizione spettrale',short:'Autovettori e spettro',part:0,pages:[60,69,96,102],intro:'Un’autodirezione conserva il proprio allineamento quando agisce la matrice; il fattore di scala è l’autovalore. Per una matrice simmetrica reale possiamo ricomporre ogni vettore a partire da due direzioni ortogonali.',bridge:'La base propria è una scelta di coordinate particolarmente utile. Esaminiamo come cambiano le matrici quando cambiamo base e come conta l’ordine delle operazioni.'},
{id:'composizione',title:'Cambio di base e ordine delle operazioni',short:'Basi e composizione',part:0,pages:[77],intro:'Una trasformazione può essere descritta in basi differenti. Le matrici cambiano perché cambiano le coordinate. Due trasformazioni successive richiedono invece di seguire l’ordine in cui agiscono sul vettore.',bridge:'Per descrivere due sistemi insieme dobbiamo costruire una base le cui etichette conservino entrambe le alternative.'},
{id:'tensore',title:'Costruire uno spazio composto',short:'Prodotto tensoriale',part:0,pages:[89],intro:'Il prodotto tensoriale associa a ogni coppia di componenti il loro prodotto. Per due vettori a due componenti si ottengono quattro ampiezze, ordinate secondo la base 00, 01, 10, 11.',bridge:'Le ampiezze consentiranno di calcolare probabilità. Prima di collegarle agli stati quantistici precisiamo come descrivere esiti e distribuzioni.'},
{id:'eventi',title:'Dagli esiti agli eventi',short:'Esiti e variabili',part:1,pages:[111,117],intro:'Un evento raccoglie alcuni degli esiti possibili. Una variabile aleatoria assegna un numero a ogni esito; quando più esiti ricevono lo stesso numero, le loro probabilità si sommano.',bridge:'Una distribuzione può essere descritta anche attraverso il suo valore medio e la dispersione dei valori attorno alla media.'},
{id:'momenti',title:'Media e dispersione',short:'Media e varianza',part:1,pages:[122,127],intro:'La media è il baricentro dei valori, ciascuno pesato dalla propria probabilità. Gli scarti quadratici, pesati nello stesso modo, descrivono la dispersione della distribuzione.',bridge:'Ripetendo un esperimento raccogliamo valori casuali. La distribuzione dei conteggi descrive le variazioni fra raccolte diverse.'},
{id:'frequenze',title:'Prove ripetute e frequenze',short:'Binomiale e frequenze',part:1,pages:[134,141],intro:'Ogni raccolta contiene N prove indipendenti con la stessa probabilità p di successo. Ripetendo l’intera raccolta possiamo osservare la distribuzione del conteggio K e della frequenza K/N.',bridge:'Un’informazione aggiuntiva può selezionare una parte degli esiti. Le probabilità devono allora essere riferite al sottoinsieme rimasto.'},
{id:'condizionamento',title:'Condizionamento e distribuzioni congiunte',short:'Condizionamento e Bayes',part:1,pages:[147,153],intro:'Una tabella congiunta conserva simultaneamente due proprietà degli esiti. Le somme di righe e colonne danno le marginali; selezionare una riga o una colonna definisce una probabilità condizionata.',bridge:'Torniamo ora alle ampiezze: vettori complessi normalizzati descrivono preparazioni dalle quali ricavare le probabilità delle misure.'},
{id:'stati',title:'Componenti, ket, bra e sfera di Bloch',short:'Dal vettore allo stato',part:2,pages:[164,174],intro:'Un qubit puro è descritto da due ampiezze complesse la cui norma quadra totale vale uno. Ket e bra rendono esplicito il ruolo dei vettori nei prodotti; la sfera raccoglie gli stati che differiscono soltanto per una fase globale.',bridge:'Le operazioni unitarie trasformano le ampiezze conservandone la norma e inducono rotazioni sulla sfera.'},
{id:'unitarie',title:'Trasformare uno stato',short:'Operatori sul qubit',part:2,pages:[189],intro:'Seguiamo lo stato attraverso una sequenza di operazioni. Ogni blocco agisce sulle due ampiezze e produce l’ingresso del blocco successivo; la geometria e il prodotto matriciale descrivono gli stessi passaggi.',bridge:'Per ricavare gli esiti occorre specificare la base di misura. Le componenti dello stato in questa base determinano le probabilità.'},
{id:'born',title:'Orientare una misura',short:'Proiettori e regola di Born',part:2,pages:[183,198,204,212],intro:'Una misura proiettiva ideale associa gli esiti a sottospazi ortogonali. Nel caso non degenere del qubit, ogni esito corrisponde a un autostato: la componente lungo quell’autostato determina la probabilità e lo stato condizionato.',bridge:'Le probabilità permettono di calcolare medie e dispersioni, che dipendono sia dalla preparazione sia dall’osservabile.'},
{id:'incompatibilita',title:'Dispersioni e osservabili incompatibili',short:'Medie e incompatibilità',part:2,pages:[220,226],intro:'Confrontiamo due osservabili sulla stessa preparazione. Le dispersioni descrivono distribuzioni ottenute su molte copie dello stato; le sequenze di misura richiedono invece di aggiornare lo stato dopo ogni esito.',bridge:'Quando i sistemi sono due, occorre conservare le ampiezze e le statistiche congiunte: la sola descrizione di ciascun sistema può essere insufficiente.'},
{id:'composti',title:'Due qubit e correlazioni',short:'Sistemi composti',part:2,pages:[235],intro:'Le quattro ampiezze di due qubit descrivono le alternative 00, 01, 10 e 11. Uno stato prodotto si ricostruisce da due vettori locali; uno stato entangled richiede la descrizione congiunta.',bridge:'Gli strumenti del capitolo possono ora essere applicati, nello stesso calcolo, a un’osservabile e a una preparazione assegnate.'},
{id:'esperimento',title:'Un esperimento dall’inizio alla fine',short:'Il calcolo completo',part:2,pages:[242],intro:'Riprendiamo il problema conclusivo della lezione: dall’operatore e dallo stato ricaviamo gli esiti, le loro probabilità, media e dispersione; infine calcoliamo lo stato condizionato all’esito maggiore.',bridge:'Il simulatore dispone ora di una descrizione dello stato, delle trasformazioni e della misura. I capitoli successivi svilupperanno questo percorso.'}
];
export const courseTitle='Quantum e post-quantum computing';
export const courseChapters=[{id:1,title:'Dal determinismo al calcolo quantistico',count:10,accent:'coral',intro:'Dai dati iniziali di una particella alle ampiezze di un qubit: seguiamo le informazioni che una simulazione deve conservare per produrre previsioni.'},{id:2,title:'Geometria del calcolo quantistico',count:18,accent:'violet',intro:'Vettori, trasformazioni e probabilità danno una forma matematica agli esperimenti del primo capitolo. Figure e calcoli descrivono insieme ogni passaggio.'}];
export const futureChapters=[{id:'future',title:'Capitoli successivi',status:'To be done'}];
