'use client';
import React,{useEffect,useId,useRef,useState,createContext,useContext,type ReactNode} from 'react';
import {type R2,type R3,type V,type Mat,f,cz,mul,add,z,abs2} from './math/core';
import {BlochPoint} from '@/components/bloch-point';
export const K={blue:'var(--mq-blue)',violet:'var(--mq-violet)',teal:'var(--mq-green)',coral:'var(--mq-coral)',amber:'var(--mq-amber)',ink:'var(--mq-text)',line:'var(--mq-line)'};
export const AssetsContext=createContext({base:'./',chapter:2});
export function Equation({children}:{children:ReactNode}){return <div className="equation">{children}</div>;}
export function Matrix({a,label}:{a:Mat;label?:string}){return <span className="matrix-wrap">{label&&<span>{label} = </span>}<span className="matrix" role="table" aria-label={label||'Matrice'}>{a.map((row,i)=><span className="matrix-row" role="row" key={i}>{row.map((x,j)=><span role="cell" key={j}>{cz(x)}</span>)}</span>)}</span></span>;}
export function Column({v,label}:{v:V;label?:string}){return <Matrix a={v.map(x=>[x])} label={label}/>;}
export function Frac({a,b}:{a:ReactNode;b:ReactNode}){return <span className="fraction"><span>{a}</span><span>{b}</span></span>;}
export function Field({label,value,onChange,min=-5,max=5,step=.1,note,unit='',disabled=false}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number;note?:string;unit?:string;disabled?:boolean}){
 const lower=Math.min(min,value),upper=Math.max(max,value);const id=useId(),[draft,setDraft]=useState<string|null>(null);const parse=(s:string)=>{const q=Number(s.trim().replace('−','-').replace(',','.'));return s.trim()&&!/^[+−-]$/.test(s)&&Number.isFinite(q)&&q>=lower&&q<=upper?q:null;};const invalid=draft!==null&&parse(draft)===null;
 return <div className="geo-field"><div className="geo-field-top"><label htmlFor={id}>{label}</label><span><input id={id} inputMode="decimal" type="text" value={draft??String(Number(value.toPrecision(10)))} disabled={disabled} aria-invalid={invalid} onFocus={()=>setDraft(String(Number(value.toPrecision(10))))} onChange={e=>{setDraft(e.target.value);const n=parse(e.target.value);if(n!==null)onChange(n);}} onBlur={()=>setDraft(null)} onKeyDown={e=>{if(e.key==='Enter'||e.key==='Escape')e.currentTarget.blur();}}/>{unit}</span></div><input type="range" aria-label={label+' · cursore'} value={value} min={lower} max={upper} step={step} disabled={disabled} onChange={e=>{setDraft(null);onChange(Number(e.target.value));}}/>{invalid&&<p className="field-error">Intervallo ammesso: {min}–{max}. Resta applicato {f(value)}.</p>}{note&&<p>{note}</p>}</div>;
}
export function Select({label,value,onChange,options,note}:{label:string;value:string;onChange:(x:string)=>void;options:[string,string][];note?:string}){const id=useId();return <div className="geo-field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select>{note&&<p>{note}</p>}</div>;}
export function Presets({items}:{items:{label:string;onClick:()=>void;active?:boolean}[]}){return <div className="geo-presets" aria-label="Esempi predisposti">{items.map((p,i)=><button key={i} aria-pressed={p.active} onClick={p.onClick}>{p.label}</button>)}</div>;}
export function VectorFields({name,v,onChange,max=4}:{name:string;v:number[];onChange:(v:number[])=>void;max?:number}){return <fieldset className="vector-fields"><legend>{name}</legend>{v.map((x,i)=><Field key={i} label={name+['₁','₂','₃'][i]} value={x} min={-max} max={max} onChange={n=>onChange(v.map((q,j)=>j===i?n:q))}/>)}</fieldset>;}
export type Step={title:string;formula:ReactNode;text:string};
export const StepContext=createContext({active:-1,setActive:(_:number)=>{}});
export function download(name:string,data:string,type='text/plain'){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function Lesson({children,controls,steps,interpretation,theory,scope,data}:{children:ReactNode|((active:number)=>ReactNode);controls:ReactNode;steps:Step[];interpretation:ReactNode;theory:ReactNode;scope:string;data:unknown}){
 const [active,setActive]=useState(0),[all,setAll]=useState(true),[playing,setPlaying]=useState(false),[expanded,setExpanded]=useState(false);const ref=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{setActive(i=>Math.min(i,steps.length-1));},[steps.length]);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setActive(a=>{if(a>=steps.length-1){setPlaying(false);return a;}return a+1;}),2400);return()=>clearInterval(id);},[playing,steps.length]);useEffect(()=>{if(expanded)dialog.current?.showModal();else if(dialog.current?.open)dialog.current.close();},[expanded]);
 const exportLesson=()=>{
  const el=ref.current;if(!el)return;
  const title=document.querySelector('h1')?.textContent||'Dimostrazione',escape=(t:string)=>t.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  const sections=['.geo-theory','.geo-visual','.geo-caption'];
  const copy=(node:Element)=>{const c=node.cloneNode(true) as HTMLElement;c.querySelectorAll('.view-controls,.bloch-drag-hint,.probability-actions,input,select').forEach(x=>x.remove());c.querySelectorAll('button').forEach(button=>{const label=document.createElement('span');label.className=button.className+' static-control';label.innerHTML=button.innerHTML;if(button.getAttribute('aria-pressed'))label.setAttribute('data-selected',button.getAttribute('aria-pressed')!);button.replaceWith(label);});c.removeAttribute('hidden');return c.outerHTML;};
  const content=sections.map(q=>el.querySelector(q)).filter((x):x is Element=>!!x).map(copy).join('')+Array.from(el.querySelectorAll('.geo-step')).map(copy).join('');
  const css=Array.from(document.styleSheets).map(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText).join('\n');}catch{return '';}}).join('\n');
  download('dimostrazione.html',`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>${css}
body{margin:0;background:var(--mq-bg)}.export-document{max-width:1200px;margin:auto;padding:32px;min-height:100vh}.export-document svg{max-width:100%}.static-control{display:inline-block;padding:10px;border:1px solid var(--mq-line);border-radius:8px;background:var(--mq-surface)}.tensor-grid>.static-control,.event-mosaic>.static-control{display:flex;flex-direction:column;align-items:center}.static-control[data-selected=true]{outline:2px solid var(--mq-blue)}.event-mosaic .static-control.selected{border:2px solid var(--mq-coral);background:var(--mq-raised)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.export-document .geo-step{display:block!important}.export-document .geo-track{height:21px}.export-document .geo-track>div{height:100%}</style><body><main class="course-app export-document"><h1>${escape(title)}</h1><p>Configurazione conservata al momento dell’esportazione. Figure, probabilità e calcoli si riferiscono agli stessi dati.</p>${content}<h2>Condizioni della rappresentazione</h2><p>${escape(scope)}</p><details><summary>Dati della configurazione</summary><pre>${escape(JSON.stringify(data,null,2))}</pre></details></main></body></html>`,'text/html');
 };
 return <StepContext.Provider value={{active,setActive}}><div className="lesson" ref={ref}><section className="geo-theory"><h2>La costruzione matematica</h2>{theory}</section><div className="geo-workspace"><aside className="geo-controls"><h2>Regolazioni</h2>{controls}</aside><section className="geo-stage"><div className="geo-stage-head"><span>GEOMETRIA E DATI</span><button onClick={()=>setExpanded(true)}>Ingrandisci</button></div><div className="geo-visual">{typeof children==='function'?children(active):children}</div><div className="geo-caption">{interpretation}</div></section></div><section className="geo-calculation"><div className="calculation-head"><div><span className="eyebrow">DAL DISEGNO AL CALCOLO</span><h2>Dal disegno ai passaggi del calcolo</h2></div><button onClick={exportLesson}>Esporta la dimostrazione</button></div><p className="precision-note">I risultati numerici sono arrotondati a quattro decimali; il simbolo ≈ indica il valore numerico. Le identità simboliche indicano le relazioni esatte; i numeri che provengono da un calcolo sono approssimati. I calcoli interni usano la precisione numerica completa.</p><div className="calculation-reference"><details open><summary>Figura della configurazione corrente</summary><div>{typeof children==='function'?children(active):children}</div><p>La figura usa gli stessi dati dei passaggi. Le regolazioni principali si trovano sopra.</p></details></div><div className="calculation-steps"><div className="step-toolbar"><button disabled={active===0} onClick={()=>{setPlaying(false);setActive(x=>Math.max(0,x-1));}}>← Passaggio</button><span>{active+1} / {steps.length}</span><button disabled={active===steps.length-1} onClick={()=>{setPlaying(false);setActive(x=>Math.min(steps.length-1,x+1));}}>Passaggio →</button><button onClick={()=>{if(active===steps.length-1)setActive(0);setPlaying(x=>!x);}}>{playing?'Pausa':'Scorri i passaggi'}</button><button aria-pressed={all} onClick={()=>setAll(x=>!x)}>{all?'Concentrati sul passaggio':'Mostra tutti i passaggi'}</button></div><div className="step-index">{steps.map((s,i)=><button key={i} aria-label={'Passaggio '+(i+1)+': '+s.title} aria-pressed={active===i} onClick={()=>{setPlaying(false);setActive(i);}}>{i+1}</button>)}</div>{steps.map((s,i)=><article key={i} className={'geo-step'+(active===i?' selected':'')} hidden={!all&&i!==active} onClick={()=>setActive(i)}><h3><span>{String(i+1).padStart(2,'0')}</span>{s.title}</h3><Equation>{s.formula}</Equation><p>{s.text}</p></article>)}</div></section><details className="geo-scope"><summary>Spazio rappresentato e condizioni</summary><p>{scope}</p></details><dialog ref={dialog} className="geo-dialog" onClose={()=>setExpanded(false)}><button autoFocus onClick={()=>setExpanded(false)}>Chiudi figura</button>{expanded&&<div className="geo-visual">{typeof children==='function'?children(active):children}</div>}</dialog></div></StepContext.Provider>;
}
export type Arrow={v:R2;from?:R2;label:string;color:string;dash?:boolean;onChange?:(v:R2)=>void;step?:number};
export function Plane({arrows,extent=4,title='Piano reale',labels=['x','y'],lines=[],circles=[],polygons=[]}:{arrows:Arrow[];extent?:number;title?:string;labels?:string[];lines?:{a:R2;b:R2;color:string;dash?:boolean}[];circles?:{r:number;color:string}[];polygons?:{points:R2[];color:string}[]}){
 const id=useId(),drag=useRef<number|null>(null),{active,setActive}=useContext(StepContext);const e=Math.max(.1,extent),s=145/e,px=(v:R2)=>[200+s*v[0],185-s*v[1]],ticks=Array.from({length:9},(_,i)=>(i-4)*e/4);
 const labelPositions:{x:number;y:number;width:number}[]=[];for(const a of arrows){const origin=a.from||[0,0],end=px([origin[0]+a.v[0],origin[1]+a.v[1]]),width=Math.min(190,Math.max(16,a.label.length*9));let x=end[0]+10;if(x+width>388)x=end[0]-width-10;x=Math.max(12,Math.min(388-width,x));let y=Math.max(30,Math.min(346,end[1]-12));for(const offset of [-12,-35,22,45,-58,68]){const candidate=Math.max(30,Math.min(346,end[1]+offset));if(![...labelPositions,{x:348,y:179,width:40},{x:207,y:37,width:32}].some(p=>x<p.x+p.width+7&&x+width+7>p.x&&Math.abs(candidate-p.y)<21)){y=candidate;break;}}labelPositions.push({x,y,width});}
 const move=(ev:React.PointerEvent<SVGSVGElement>)=>{if(drag.current===null)return;const m=ev.currentTarget.getScreenCTM();if(!m)return;const p=ev.currentTarget.createSVGPoint();p.x=ev.clientX;p.y=ev.clientY;const q=p.matrixTransform(m.inverse()),a=arrows[drag.current],o=a.from||[0,0];a.onChange?.([Math.max(-e,Math.min(e,(q.x-200)/s-o[0])),Math.max(-e,Math.min(e,(185-q.y)/s-o[1]))]);};
 return <figure className="geo-plane"><figcaption>{title}</figcaption><svg viewBox="0 0 400 380" role="img" aria-label={title} onPointerMove={move} onPointerUp={ev=>{move(ev);drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}><defs>{arrows.map((a,i)=><marker id={id+'a'+i} key={i} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill={a.color}/></marker>)}</defs><rect x="32" y="17" width="336" height="336" rx="14" fill="var(--mq-panel)"/>{ticks.map(t=><g key={t}><path d={`M${200+t*s} 40V330M55 ${185-t*s}H345`} stroke={t===0?'var(--mq-muted)':'var(--mq-line)'} strokeWidth={t===0?1.5:1}/>{t!==0&&<><text x={200+t*s} y="204" textAnchor="middle" fontSize="14" fill="var(--mq-muted)">{f(t,2)}</text><text x="191" y={189-t*s} textAnchor="end" fontSize="14" fill="var(--mq-muted)">{f(t,2)}</text></>}</g>)}<text x="351" y="179" fill={K.ink} fontSize="16">{labels[0]}</text><text x="210" y="37" fill={K.ink} fontSize="16">{labels[1]}</text>{circles.map((c,i)=><circle key={i} cx="200" cy="185" r={c.r*s} fill="none" stroke={c.color} strokeDasharray="5 5"/>)}{polygons.map((p,i)=><polygon key={i} points={p.points.map(v=>px(v).join(',')).join(' ')} fill={p.color} fillOpacity=".12" stroke={p.color} strokeOpacity=".5"/>)}{lines.map((l,i)=><line key={i} x1={px(l.a)[0]} y1={px(l.a)[1]} x2={px(l.b)[0]} y2={px(l.b)[1]} stroke={l.color} strokeWidth="1.8" strokeDasharray={l.dash?'5 5':undefined}/>)}{arrows.map((a,i)=>{const o=a.from||[0,0],end:R2=[o[0]+a.v[0],o[1]+a.v[1]],[x,y]=px(end),[ox,oy]=px(o);return <g key={i} opacity={a.step!==undefined&&active!==a.step? .65:1} onClick={()=>a.step!==undefined&&setActive(a.step)}><line x1={ox} y1={oy} x2={x} y2={y} stroke={a.color} strokeWidth={a.step===active?4.5:3} strokeDasharray={a.dash?'5 4':undefined} markerEnd={Math.hypot(...a.v)>1e-9?'url(#'+id+'a'+i+')':undefined}/><circle cx={x} cy={y} r={a.onChange?7:3.5} fill={a.color} stroke="var(--mq-on-accent)" strokeWidth="2" onPointerDown={a.onChange?ev=>{ev.preventDefault();drag.current=i;ev.currentTarget.setPointerCapture(ev.pointerId);}:undefined}/><text x={labelPositions[i].x} y={labelPositions[i].y} fill={a.color} fontSize="17" fontWeight="600">{a.label}</text></g>;})}</svg>{arrows.some(x=>x.onChange)&&<p className="plot-hint">Trascina i punti pieni; i campi numerici consentono la stessa regolazione.</p>}</figure>;
}
export function Spatial({vectors,plane=false}:{vectors:{v:R3;color:string;label:string}[];plane?:boolean|R3[]}){const [yaw,setYaw]=useState(-35),[pitch,setPitch]=useState(25),planePoints:R3[]=Array.isArray(plane)?[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>plane[0].map((x,i)=>1.8*(a*x+b*plane[1][i])) as R3):[[-3,-3,0],[3,-3,0],[3,3,0],[-3,3,0]],s=Math.min(42,145/Math.max(3.5,...vectors.map(x=>Math.hypot(...x.v)),...(plane?planePoints.map(x=>Math.hypot(...x)):[0])));const p=(v:R3):R2=>{const a=yaw*Math.PI/180,b=pitch*Math.PI/180,x=v[0]*Math.cos(a)-v[1]*Math.sin(a),y=v[0]*Math.sin(a)+v[1]*Math.cos(a);return[200+s*x,185-s*(v[2]*Math.cos(b)+y*Math.sin(b))];};return <figure className="spatial"><figcaption>Spazio reale a tre dimensioni</figcaption><svg viewBox="0 0 400 370" role="img" aria-label="Vettori nello spazio reale">{plane&&<polygon points={planePoints.map(v=>p(v as R3).join(',')).join(' ')} fill={K.teal} fillOpacity=".12" stroke={K.teal}/>}{[0,1,2].map(i=>{const v=[0,0,0] as R3;v[i]=3.5;const q=p(v);return <g key={i}><line x1="200" y1="185" x2={q[0]} y2={q[1]} stroke="var(--mq-wire)"/><text x={q[0]+5} y={q[1]-5}>{['x','y','z'][i]}</text></g>;})}{vectors.map((v,i)=>{const q=p(v.v);return <g key={i}><line x1="200" y1="185" x2={q[0]} y2={q[1]} stroke={v.color} strokeWidth="4"/><circle cx={q[0]} cy={q[1]} r="5" fill={v.color}/><text x={q[0]+7} y={q[1]-8} fill={v.color}>{v.label}</text></g>;})}</svg><Field label="Vista · azimut" value={yaw} min={-180} max={180} step={1} unit="°" onChange={setYaw}/><Field label="Vista · elevazione" value={pitch} min={-80} max={80} step={1} unit="°" onChange={setPitch}/><p className="plot-hint">Questi due comandi ruotano il punto di osservazione e conservano i vettori.</p></figure>;}
export function ComplexPlanes({v,labels,title='Componenti complesse',extent,color}:{v:V;labels?:string[];title?:string;extent?:number;color?:string}){const e=extent??Math.max(1.2,...v.map(x=>Math.hypot(...x)*1.3));return <div className="complex-planes" aria-label={title}>{v.map((x,i)=><Plane key={i} title={labels?.[i]||'Componente '+i} extent={e} labels={['Re','Im']} arrows={[{v:x,label:labels?.[i]||'c'+i,color:color||(i%2?K.coral:K.teal)}]} circles={[{r:1,color:'var(--mq-wire)'}]}/>)}</div>;}
export function Sphere({v,onChange,axis,path,angleTo,label='Stato sulla sfera di Bloch'}:{v:R3;onChange?:(v:R3)=>void;axis?:R3;path?:R3[];angleTo?:R3;label?:string}){return <figure className="course-sphere"><figcaption>{label}</figcaption><BlochPoint v={v} onChange={onChange} axis={axis} path={path} angleTo={angleTo} showAxes label={label}/><p className="sphere-coordinates">r ≈ ({v.map(x=>f(x,3)).join('; ')})</p></figure>;}
export function Bars({values,labels,title='Probabilità',compare,percent=true}:{values:number[];labels:string[];title?:string;compare?:number[];percent?:boolean}){const max=percent?1:Math.max(1,...values,...compare||[]);return <figure className="geo-bars"><figcaption>{title}</figcaption>{values.map((v,i)=><div className="geo-bar" key={i}><span>{labels[i]}</span><div className="geo-track"><div style={{width:Math.max(0,v/max*100)+'%',background:[K.teal,K.coral,K.blue,K.violet][i%4]}}/>{compare&&<i style={{left:Math.max(0,compare[i]/max*100)+'%'}}/>}</div><strong>{percent?f(v*100,2)+'%':f(v,3)}</strong></div>)}{compare&&<p>La barra mostra la frequenza; il tratto verticale indica la probabilità teorica.</p>}</figure>;}
export function Stat({label,value,color=K.blue}:{label:string;value:ReactNode;color?:string}){return <div className="geo-stat" style={{borderColor:color}}><span>{label}</span><strong style={{color}}>{value}</strong></div>;}
export function Note({children}:{children:ReactNode}){return <div className="geo-note">{children}</div>;}
export function ProductWork({a,b,name='C'}:{a:Mat;b:Mat;name?:string}){return <div className="product-work">{a.map((row,i)=>b[0].map((_,j)=><div key={i+','+j}>{name}{['₁','₂','₃','₄'][i]}{['₁','₂','₃','₄'][j]} = {row.map((x,k)=>`(${cz(x)})·(${cz(b[k][j])})`).join(' + ')} ≈ {cz(row.reduce((sum,x,k)=>add(sum,mul(x,b[k][j])),z()))}</div>))}</div>;}

export function EigenvectorWork({a,lambda,u,index}:{a:Mat;lambda:number;u:V;index:number}){
 const pivot=abs2(u[1])>=abs2(u[0])?1:0,other=1-pivot,shift=a.map((row,i)=>row.map((x,j)=>[x[0]-(i===j?lambda:0),x[1]] as [number,number])),row=abs2(shift[0][other])>=abs2(shift[1][other])?0:1,den=u[pivot],raw=u.map(x=>{const n=abs2(den);return[(x[0]*den[0]+x[1]*den[1])/n,(x[1]*den[0]-x[0]*den[1])/n] as [number,number];}),length=Math.sqrt(raw.reduce((sum,x)=>sum+abs2(x),0)),factor:[number,number]=[u[pivot][0]/Math.hypot(...u[pivot]),u[pivot][1]/Math.hypot(...u[pivot])];
 return <><p>Una componente non nulla può essere scelta liberamente: fissiamo w{pivot+1}=1. Sostituendo nelle equazioni si ricava l’altra componente.</p><div>({cz(shift[row][other])})w{other+1} + ({cz(shift[row][pivot])})·1 = 0</div>{abs2(shift[row][other])>0?<div>w{other+1} = −({cz(shift[row][pivot])})/({cz(shift[row][other])}) ≈ {cz(raw[other])}</div>:<div>Entrambe le equazioni sono 0=0: scegliamo la direzione canonica indicata.</div>}<div>w{2-pivot} ≈ {cz(raw[1-pivot])}; w ≈ ({raw.map(x=>cz(x)).join('; ')})ᵀ</div><div>‖w‖² = {raw.map(x=>`(${f(x[0])})²+(${f(x[1])})²`).join(' + ')} ≈ {f(length*length)}</div><div>‖w‖ ≈ {f(length)}; ŵ = w/‖w‖ ≈ ({raw.map(x=>cz([x[0]/length,x[1]/length])).join('; ')})ᵀ</div><p>Si può moltiplicare ŵ per un fattore di fase di modulo uno. Per mantenere la stessa convenzione della figura usiamo il rappresentante seguente, che appartiene alla medesima autodirezione.</p><div>η = u{pivot+1}/|u{pivot+1}| ≈ {cz(factor)}; |η|² ≈ {f(abs2(factor))}</div><div>u = η ŵ ≈ ({raw.map(x=>cz(mul(factor,[x[0]/length,x[1]/length]))).join('; ')})ᵀ</div><Column label={'u'+['₁','₂'][index]} v={u}/></>;
}
