// One palette for screen, print, Canvas and PDF. Edit the JSON, not the generated CSS.
import fs from 'node:fs';
const base=new URL('../src/course/',import.meta.url);
const palette=JSON.parse(fs.readFileSync(new URL('matrix-palette.json',base),'utf8'));
const declarations=p=>Object.entries(p).map(([key,value])=>`  --mq-${key}:${value};`).join('\n');
fs.writeFileSync(new URL('matrix-palette.css',base),`/* Generated by scripts/generate-theme.mjs from matrix-palette.json. */\n:root {\n${declarations(palette.screen)}\n}\n@media print {\n  :root {\n${declarations(palette.print)}\n  }\n}\n`);
