import './generate-theme.mjs';
// Render read-only demonstrations for guides and deterministic structural checks.
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {build} from 'esbuild';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),src=path.join(root,'src'),out=path.join(root,'qa/course');await fs.mkdir(out,{recursive:true});
const entry=path.join(out,'rendered.cjs');
await build({stdin:{contents:`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import App,{chapterTwoComponents,parseRoute} from './course/app';import {chapterOne,ChapterOneDemo} from './course/chapter-one';import {chapterTwo,courseChapters} from './course/catalogue';
export const chapters=courseChapters;
export const views=[...chapterOne.map((d,i)=>({chapter:1,index:i,id:d.id,title:d.title,intro:d.question,pages:[d.page],part:0,html:render(<App initialChapter={1} initialDemo={d.id}/>),demo:render(<div className="chapter-one-content"><ChapterOneDemo index={i}/></div>)})),...chapterTwo.map((d,i)=>{const Demo=chapterTwoComponents[i];return {...d,chapter:2,index:i,html:render(<App initialChapter={2} initialDemo={d.id}/>),demo:render(<div className="chapter-two-content"><Demo/></div>)}})];
export const coverViews=[0,1,2].map(c=>({chapter:c,html:render(<App initialChapter={c}/>)}));
export const routing={old:chapterOne.map(d=>parseRoute('#'+d.id)),new:chapterTwo.map(d=>parseRoute('#capitolo-2/'+d.id))};`,resolveDir:src,loader:'tsx'},bundle:true,platform:'node',format:'cjs',jsx:'automatic',alias:{'@':src},external:['react','react-dom','react-dom/server','react/jsx-runtime'],outfile:entry,logLevel:'silent'});
const require=createRequire(import.meta.url),{views,chapters,coverViews,routing}=require(entry);
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const toc=chosen=>chosen.map(c=>`<section><h2>Capitolo ${c.id} · ${escape(c.title)}</h2><ol>${views.filter(v=>v.chapter===c.id).map(v=>`<li><a href="#c${c.id}-${v.id}">${c.id}.${String(v.index+1).padStart(2,'0')} · ${escape(v.title)}</a></li>`).join('')}</ol></section>`).join('');
const tailwindPath=require.resolve('@tailwindcss/postcss'),postcss=createRequire(tailwindPath)('postcss'),tailwind=(await import(tailwindPath)).default;
const cssPath=path.join(src,'app/globals.css'),css=(await postcss([tailwind({base:src})]).process(await fs.readFile(cssPath,'utf8'),{from:cssPath})).css;
const guide=chosen=>`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guida al laboratorio · Quantum e post-quantum computing</title><style>${css}
body{margin:0;background:var(--mq-panel)}.guide-book{max-width:1100px;margin:auto;padding:35px 28px}.guide-cover{padding:25px 0 45px}.guide-cover h1{font-size:48px}.guide-book p{font-family:Georgia;line-height:1.85}.guide-toc{padding:25px;background:var(--mq-surface);border-radius:15px}.guide-toc a{color:var(--mq-muted)}.guide-toc li{padding:5px 0}.guide-chapter{border-top:5px solid var(--mq-violet);margin-top:70px;padding-top:35px}.guide-demo{padding-top:30px;margin-top:45px;border-top:1px solid var(--mq-wire);scroll-margin-top:20px}.guide-demo h2{font-size:32px}.guide-demo h3{margin-top:22px}.guide-live{display:inline-block;padding:8px 14px;background:var(--mq-surface);border-radius:7px;margin-bottom:20px;color:var(--mq-blue)}.guide-book .geo-controls,.guide-book button,.guide-book input,.guide-book select,.guide-book .step-toolbar,.guide-book .step-index,.guide-book .reading-nav,.guide-book .control-panel,.guide-book .source-settings,.guide-book .bloch-drag-hint,.guide-book .view-controls,.guide-book .figure-toolbar,.guide-book .experiment-actions,.guide-book .continuous-controls,.guide-book .lab-notebook{display:none!important}.guide-book .geo-workspace,.guide-book .experiment-layout{display:block}.guide-book .geo-step[hidden]{display:block!important}.guide-book .geo-calculation{margin-top:25px}.guide-book svg{width:100%;max-height:430px;display:block}.guide-book .geo-plots{grid-template-columns:1fr 1fr}.guide-book .tensor-grid>button,.guide-book .event-mosaic>button{display:flex!important;pointer-events:none}.guide-book canvas{display:none}.guide-book .lab-introduction,.guide-book .lab-discussion,.guide-book .figure-explanation,.guide-book .observation{font:17px/1.85 Georgia;margin:24px 0}.guide-book .chapter-one-content{overflow:hidden}.guide-book .geo-scope[open]{display:block}.guide-book .geo-scope{font:16px Georgia}.guide-book .geo-stage-head{display:none}.guide-book .geo-note{padding:17px}.guide-book .result-columns{display:none}.guide-book .probability-row{padding:6px;border-bottom:1px solid var(--mq-surface)}.guide-book .probability-row>span{margin-right:18px}@media(max-width:650px){.guide-book{padding:22px 16px}.guide-cover h1{font-size:36px}.guide-book .geo-plots{grid-template-columns:1fr}.guide-book .equation{font-size:18px}}@media print{.guide-demo{break-before:page}.guide-live{display:none}.guide-book{padding:0}.guide-chapter{break-before:page}.guide-book .geo-plots{grid-template-columns:1fr 1fr}}
.guide-book .calculation-reference,.guide-book .notebook-navigation,.guide-book .experiment-presets{display:none!important}.guide-book .geo-controls,.guide-book .notebook-controls{display:block!important;margin:20px 0;background:var(--mq-panel);border:1px solid var(--mq-surface)}.guide-book .notebook-bench{display:block}.guide-book .quantum-circuit button,.guide-book .tensor-grid>button,.guide-book .event-mosaic>button,.guide-book .joint-table button{display:inline-flex!important;opacity:1;pointer-events:none}.guide-book .model-details,.guide-book .geo-scope{display:block}.guide-book .model-details>div{display:block}.guide-book .geo-calculation{display:block}.guide-book .geo-track{height:21px}.guide-book .geo-track>div{height:100%}.guide-book .complex-planes{grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr))}.guide-book .stage svg{min-width:0;max-height:none}.guide-book .geo-plots{grid-template-columns:repeat(auto-fit,minmax(min(100%,350px),1fr))}
</style><body><main class="course-app guide-book"><header class="guide-cover"><span class="eyebrow">GUIDA ALLE DIMOSTRAZIONI</span><h1>Quantum e post-quantum computing</h1><p>${chosen.length===2?'Due capitoli collegano la costruzione di una simulazione alla sua descrizione matematica.':'Questa guida accompagna il capitolo '+chosen[0].id+' del corso.'} Questa guida raccoglie le configurazioni iniziali, le figure e gli svolgimenti delle dimostrazioni. I collegamenti aprono il laboratorio, nel quale i parametri possono essere modificati.</p><p>Marzio De Corato · Danilo Bruschi · Università degli Studi di Milano</p><a href="./index.html">Apri l’indice del corso ↗</a> · <a href="./Guida_corso.pdf">Guida PDF ↗</a></header><nav class="guide-toc" aria-label="Indice della guida">${toc(chosen)}</nav>${chosen.map(c=>`<section class="guide-chapter" id="capitolo-${c.id}"><span class="eyebrow">CAPITOLO ${c.id}</span><h1>${escape(c.title)}</h1><p>${escape(c.intro)}</p>${views.filter(v=>v.chapter===c.id).map(v=>`<article class="guide-demo" id="c${c.id}-${v.id}"><span class="eyebrow">DIMOSTRAZIONE ${c.id}.${String(v.index+1).padStart(2,'0')}</span><h2>${escape(v.title)}</h2><p>${escape(v.intro)}</p><a class="guide-live" href="./index.html#capitolo-${c.id}/${v.id}">Apri la dimostrazione interattiva ↗</a><p>Slide: p. ${v.pages.join(', ')}. Le figure seguenti si riferiscono alla configurazione iniziale.</p>${v.demo.replaceAll('<button','<button disabled tabindex="-1"').replaceAll('<details','<details open')}</article>`).join('')}</section>`).join('')}<section class="guide-chapter"><h2>Capitoli successivi</h2><p>To be done.</p></section></main></body></html>`;
await fs.writeFile(path.join(root,'public/guida-corso.html'),guide(chapters));
for(const chapter of chapters)await fs.writeFile(path.join(root,`public/guida-capitolo-${chapter.id}.html`),guide([chapter]));
await fs.copyFile(path.join(root,'public/guida-capitolo-1.html'),path.join(root,'public/guida-studenti.html'));
await fs.copyFile(path.join(root,'docs/corso/GUIDA_DOCENTE.md'),path.join(root,'docs/GUIDA_DOCENTE.md'));
await fs.writeFile(path.join(out,'views.json'),JSON.stringify({views,coverViews,routing,chapters}));
await fs.unlink(entry);
console.log(JSON.stringify({guide:'public/guida-corso.html',demonstrations:views.length,chapters:chapters.length}));
